### ISSUE TITLE
🐞[Bug]: Align the cards in about section

### ISSUE THREAD

**Issue by Soujanya2004** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The 4 cards in the about section is placed one in each row, I can align them next to each other for better visibility.
![Screenshot (133)](https://github.com/user-attachments/assets/cd8bd3fd-ebaf-404e-ba66-a6617e4c251c)

### Expected behavior

place 2 cards in a row

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@varshith257  Can I work on this

**Comment by varshith257** [comment]
Here you go @Soujanya2004

**Comment by Soujanya2004** [comment]
please review @varshith257

**Comment by Soujanya2004** [comment]
@varshith257 please review
