### ISSUE TITLE
Separation of Code CSS & JS Code

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1005]
### Issue Description

To move the CSS and JS code to separate files.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue.

**Comment by Soujanya2004** [comment]
hi I would like to work on this
