### ISSUE TITLE
🐞[Bug]: align button

### ISSUE THREAD

**Issue by Soujanya2004** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

align 'get started' button in dex.html to center
![Screenshot (142)](https://github.com/user-attachments/assets/54ccb45e-cff6-42ce-89f8-6cc0ff050e58)

### Expected behavior

![Screenshot (141)](https://github.com/user-attachments/assets/ceb93bd8-04e1-4c23-8b3e-5ff1a6736eb4)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@varshith257  shall I implement this

**Comment by varshith257** [comment]
> @varshith257  shall I implement this

Yes it should be in center

**Comment by Soujanya2004** [comment]
@varshith257
