### ISSUE TITLE
📝[Docs]: Content of the body is not aligned in proper way!!!

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#102]
**What Docs changes are you proposing?**
To change the box model of the document.

**Why do the Docs need this improvement?**
Such that it fits to the screen in proper way.

**Current Document Screenshot**
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/dedf9da3-59fd-42ad-84bc-71537f284314)

gaps around the content of the body.

Please assign this issue under GSSOC'24

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by Anishkagupta04** [comment]
ANY UPDATES?

**Comment by Anjaliavv51** [comment]
No , @Anishkagupta04 we can close this as it is already resolved
