### ISSUE TITLE
✨[Feature Request]: Sending confirmation email upon Subscribing

### ISSUE THREAD

**Issue by Bhattu-Anitha-07** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

User will recieve a confirmation email upon successfully subscribing to the website. And giving a alert upon subscribing.

### Use Case

Can be accessed securely.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Bhattu-Anitha-07** [comment]
@Anishkagupta04 @varshith257 
Kindly assign this issue to me, Will work on this.
Thank you.

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 
I’ve used EmailJS to send emails upon subscribing. Do I need to share my service ID, user ID, and other credentials in the PR?

**Comment by varshith257** [comment]
No need of it. Just proving de a video from your local of its working

**Comment by Bhattu-Anitha-07** [comment]
Ok @varshith257
