### ISSUE TITLE
💡[FEATURE]: 🌟 Reveal Elements On Scroll 🌟 

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#103]
**Is your feature request related to a problem? Please describe.**
No

**###Your Document has some no reveal elements on scroll feature**
**About Feature**
Ever wondered how websites smoothly reveal content as you scroll? 
Do u also want to try it ❓
It’s time to try it out! 🚀
🔍 Use Scrollreveal() in JavaScript to create captivating scroll animations. Elements will gracefully appear, adding that extra touch of magic to your web pages. ✨

> How Described feauture looks like!!!

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/b1a82dc7-267e-4721-bd2b-40498ca81b6b

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by Anishkagupta04** [comment]
@Anjaliavv51 I'm assigning you this

**Comment by Anjaliavv51** [comment]
Okay , i will start.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Anishkagupta04

**Comment by Yuvraj960** [comment]
@Anishkagupta04 @varshith257 Please assign this issue to me under GSSoC24

**Comment by Anjaliavv51** [comment]
@varshith257 please review the chnages

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes.
