### ISSUE TITLE
💡[FEATURE]:  Add Slack Logo and link in the README

### ISSUE THREAD

**Issue by varshith257** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#104]
We created a Slack channel recently for our project to interact contributors with mentors. Need to update the README with its logo and the channel link:

- https://join.slack.com/t/newworkspace-ley5153/shared_invite/zt-2isvflg78-tMexsn50mxdwY4BEJ_W11g

Contributions Welcome 🚀

**Comment by MrCodYrohit** [comment]
@varshith257 Please assign this issue to me, I will try to fix this issue within 24 hours.

**Comment by varshith257** [comment]
> @varshith257 Please assign this issue to me, I will try to fix this issue within 24 hours.

@MrCodYrohit It's a small fix can be implemented within 10 minutes. @Arpcoder will work on it and thanks for your enthusiasm to contribute for this project

**Comment by Arpcoder** [comment]
@varshith257 Please change the syntax of labels from 'GSSOC 24' to 'gsoc' and 'Level 1' to 'level1' as per the requirement under GSSoC. Thank you.

**Comment by varshith257** [comment]
> @varshith257 Please change the syntax of labels from 'GSSOC 24' to 'gsoc' and 'Level 1' to 'level1' as per the requirement under GSSoC. Thank you.

Ok, I will add it. Thanks for reminding

**Comment by MrCodYrohit** [comment]
@varshith257 Now, please reassign me, I will fix it in 10 mins.
