### ISSUE TITLE
🐞[Bug]: proper aligning

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Patient Portal 

Size decrement of the container

### Feedback Section

size decrement if your feedback input

### Add ScreenShots

Below ss from the deploy of the repo.

![image](https://github.com/user-attachments/assets/83bd8e1c-594a-4ab3-bda6-6bb13b0be333)

![image](https://github.com/user-attachments/assets/0741c8ea-c6f6-40e5-accb-cb39ec167643)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue.

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue.

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue.

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue.

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue.

**Comment by varshith257** [comment]
@Anjaliavv51 Also see this 

![image](https://github.com/user-attachments/assets/897433b2-2c37-4c21-9734-b88921996aa2)


This distorted the navbar on the homepage breaking a gap. Could you remove it too? Better move the js code out from it to a separate file  email-validator.js

**Comment by varshith257** [comment]
![image](https://github.com/user-attachments/assets/aa4ff844-a150-4d5f-9ac1-0181dffbafb7)
Something Emergency text also appearing below the Copy Code

**Comment by Anjaliavv51** [comment]
@varshith257 yes , i observed it too.
