### ISSUE TITLE
NOT Responsive at all for mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/84a0ece1-033d-4238-996d-8443e00d5f32)

### Use Case

it should be fixed to improve the experience on all devices

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Utsavladia** [comment]
@varshith257 
Kindly review this its been 1 week

**Comment by Jay-ARORA-5572** [comment]
@Anishkagupta04
hey, I'd like to contribute in this issue.
I have read the Contributing Guidelines.
I'm a GSSOC'24 contributor.
I have starred the repository.

**Comment by Utsavladia** [comment]
@Jay-ARORA-5572 
I have already created a PR for this one kindly find other open issues..
and how is @Anishkagupta04 related to this

**Comment by Jay-ARORA-5572** [comment]
@Utsavladia ok then kindly close this issue. @Anishkagupta04

**Comment by Utsavladia** [comment]
@Jay-ARORA-5572  firstly PR will be reviewed
