### ISSUE TITLE
✨[Feature Request]: Adding Github Authentication

### ISSUE THREAD

**Issue by Ojas-Arora** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@Anishkagupta04 @varshith257 @Anjaliavv51  I want to add Twitter Authentication to the website. Kindly assign me this issue.

### Use Case

Using Authentication anyone can sign in the Page using his/her own email address.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
I think it's not needed.

**Comment by Anjaliavv51** [comment]
@Ojas-Arora instead add auth for GitHub

**Comment by Anjaliavv51** [comment]
@varshith257 labels are working.

**Comment by Ojas-Arora** [comment]
@varshith257 ok I will add Github auth
