### ISSUE TITLE
✨[Feature Request]: Improve ui of the appointment page and make it responsive

### ISSUE THREAD

**Issue by aditya-bhaumik** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i would like to fix the ui of this page also try making it responsive but atleast add all necessary things like navbar and footer

### Use Case

![image](https://github.com/user-attachments/assets/780124a9-9b91-49e7-81ed-2c83660caf54)
it would like to update the footer to match the other pages also the page does not contain the navbar

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by aditya-bhaumik** [comment]
@varshith257 please assign me this issue

**Comment by Anjaliavv51** [comment]
@varshith257 i think removal of appointment section in main page is need , as their is separate appointment page.

**Comment by Anjaliavv51** [comment]
@aditya-bhaumik please remove appointment section from the main page and also remove only the related css code of appointment section in of index.html file.

**Comment by aditya-bhaumik** [comment]
@varshith257 i have created another issue for removing the appointment section from the main page this issue was for making the appointment page responsive and add navbar and footer to it please assign me that issue

**Comment by aditya-bhaumik** [comment]
the issue is #1084
