### ISSUE TITLE
Updation in index file

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1080]
![image](https://github.com/user-attachments/assets/8b682577-d8ff-4b42-b2ea-026cf82b3731)

![image](https://github.com/user-attachments/assets/05dc3dcd-4eef-4a3f-9a84-178b4e6aeb09)

removal of one from above two as both contains same content ,CSS JS code along with HTML in about section.

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue.

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue.

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue

**Comment by Anjaliavv51** [comment]
@varshith257 please say which one can i remove cards or basic boxes from the above images.

**Comment by varshith257** [comment]
Remove 2nd image content
