### ISSUE TITLE
🐞[Bug]: change color of icons

### ISSUE THREAD

**Issue by Soujanya2004** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Icons in footer of appontment.html is not visible properly
![Screenshot (153)](https://github.com/user-attachments/assets/b4c4abf6-b2ea-428f-b0b4-38134d70e8d3)

### Expected behavior

use suitable colors to enhance visibility

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Jay-ARORA-5572** [comment]
@Anishkagupta04
hey, I'd like to contribute in this issue.
I have read the Contributing Guidelines.
I'm a GSSOC'24 contributor.
I have starred the repository.
