### ISSUE TITLE
✨[Feature Request]: Add navbar 

### ISSUE THREAD

**Issue by Soujanya2004** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add navbar to appointment.html page
![Screenshot (154)](https://github.com/user-attachments/assets/1e34b61c-30f5-466a-8d62-029c79de1be0)

### Use Case

for easy navigation

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@varshith257

**Comment by Soujanya2004** [comment]
@varshith257

**Comment by Jay-ARORA-5572** [comment]
@Anishkagupta04
hey, I'd like to contribute in this issue.
I have read the Contributing Guidelines.
I'm a GSSOC'24 contributor.
I have starred the repository.
