### ISSUE TITLE
💡[FEATURE]: Add Contact Us Page and News Section (GSSoC'24)

### ISSUE THREAD

**Issue by Vaibhav22p-qw** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#112]
Assigning this issue to myself for implementation. (GSSoC'24)

Contact Us Page:
-Include a form for users to submit queries or feedback.
-Display contact information such as email, phone number, and address if applicable.
-Ensure accessibility and user-friendly design.

News Section for Medicines and Doctors' News:
-Integrate a news feed or blog section focusing on medical updates, new treatments, and healthcare industry insights.
-Provide filters or categories for easy navigation (e.g., news related to medicines, doctors, health tips).
-Include options for users to subscribe to newsletters or alerts.

**Comment by Vaibhav22p-qw** [comment]
Assigning this issue to myself for implementation. (GSSoC'24)

### **_Contact Us Page:_** This page will allow users to reach out to us for any inquiries, feedback, or support they may need regarding our platform or services.

**### _News Section for Medicines and Doctors:_** We aim to include a news section that displays updates and information about medicines, healthcare, and doctors' news. This will keep our users informed about the latest developments in the medical field.

**Comment by Vaibhav22p-qw** [comment]
@varshith257 Please Assign Me To make Contact(Query)Page

**Comment by varshith257** [comment]
Level 3 to implement both features

**Comment by Vaibhav22p-qw** [comment]
ok
