### ISSUE TITLE
🐞[Bug]: Navbar is not displayed properly on the "Make an Appointment" page

### ISSUE THREAD

**Issue by AsmitaMishra24** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The navigation bar on the "Make an Appointment" page is not displayed properly. The layout seems to be broken, and not aligned correctly. This issue affects the user experience and needs to be addressed.

### Expected behavior

The navigation bar should be properly aligned.

### Add ScreenShots

![Screenshot 2024-08-05 015433](https://github.com/user-attachments/assets/6a7dae52-fc64-424b-8cf9-4b157d507a12)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Jay-ARORA-5572** [comment]
hey, I'd like to contribute in this issue.
I have read the Contributing Guidelines.
I'm a GSSOC'24 contributor.
I have starred the repository.
