### ISSUE TITLE
🐞[Bug]: Add redirect links to all components in navbar 

### ISSUE THREAD

**Issue by Soujanya2004** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

navbar in appointment.html doesn't redirect to any page on clicking any component

https://github.com/user-attachments/assets/e1d2be35-93c3-435a-9dc2-e410159f45a3

### Expected behavior

add links 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@varshith257

**Comment by Jay-ARORA-5572** [comment]
hey, I'd like to contribute in this issue.
I have read the Contributing Guidelines
 I'm a GSSOC'24 contributor
 I have starred the repository

**Comment by Soujanya2004** [comment]
@varshith257 shall I work on this
