### ISSUE TITLE
✨[Feature Request]: Add google translate on every page of the website

### ISSUE THREAD

**Issue by samarsajad** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 Add google translate on every page of the website

### Use Case

it is important to have an inclusive website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by samarsajad** [comment]
Please assign this issue to me @varshith257

**Comment by varshith257** [comment]
@samarsajad Maybe not a priority
