### ISSUE TITLE
✨[Feature Request]: add the services section of main page to the services page

### ISSUE THREAD

**Issue by aditya-bhaumik** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/03f81404-33e7-46c7-acc9-627043190170)

### Use Case

Would like to add this in the services page also

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by aditya-bhaumik** [comment]
@varshith257 please assign me this issue 

also i would like to remove the testimonail from the footer as it is not directing anywhere now

**Comment by varshith257** [comment]
It's looking fine with home page with testimonials. We don't need to redirect it.

For services you can create new page and elaborate there with services
