### ISSUE TITLE
🐞[Bug]: text not visible at login & signup page

### ISSUE THREAD

**Issue by DevGajjar28** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#1189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Text/ links are not visible at login page and it's not clearly visible, yes when hover on text/link it's visible but not clearly visible by default. 

### Expected behavior

The text/links should be clearly visible to user without any problem.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/aa41327d-e441-4e05-9450-cb5f22eccf8e)
![image](https://github.com/user-attachments/assets/70269d20-a6f2-418e-877a-3503f13e8207)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sohan-gupthak** [comment]
Is the issue still open I would love to contribute
can check out my works at [https://sohangupthaportfolio.netlify.app/](url)
