### ISSUE TITLE
🪲[Bug]: Alignment of cards in about section

### ISSUE THREAD

**Issue by Amitesh-Mishra-AM** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#120]
**Description**
### Refrence Image
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/86422382/471999d5-7733-49eb-b5dd-9c3b243f4d0b)

**Comment by Anishkagupta04** [comment]
You can work through it

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@varshith257

**Comment by Amitesh-Mishra-AM** [comment]
## I have completed the issue, fixing some more bugs that I found while working on the assigned issue, I have created the pull request #562 , Please go through that, I am closing the issue with this commit.
### Thank you for assigning me the issue.
