### ISSUE TITLE
💡[FEATURE]: adding scroll animation

### ISSUE THREAD

**Issue by RiyaaBhatt** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#122]
Hello PA,
 I am reaching out regarding a feature request for website. Specifically, I would like to propose the addition of scroll animation to enhance user experience.

Could you please consider assigning this task under GSSOC'24 for implementation? Your support in this matter would be greatly appreciated.

Thank you for your attention to this request.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by Anishkagupta04** [comment]
Already assigned
