### ISSUE TITLE
Improving displaying of doctor images

### ISSUE THREAD

**Issue by Arpcoder** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#126]
Before:-
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/100352419/d643de9a-1674-4cd3-811f-0e00e985e966)

-----------------------------------------------------------------------------------
After:-

Displaying all doctor's image in a circular profile manner.

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/100352419/d9e3fb33-b45c-4b13-adff-a0963938ce11)

**Comment by Sailza** [comment]
**As a contributor to GSSOC 2024, I'm eager to take on tasks. Could you please assign me this task for completion?**

**Comment by Nirvanjha2004** [comment]
Heyy...Can U please assign me this issue...i would love to work on this issue.....as i have done this earlier also ....Thanks

**Comment by varshith257** [comment]
@Arpcoder Are you ready to work on it?

**Comment by Arpcoder** [comment]
> @Arpcoder Are you ready to work on it?

Yes.. I have opened it. Please assign it to me. I have already worked, as I have attached the screenshot above.
