### ISSUE TITLE
File arrengement

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#13]
Arrenge the files iin a perticular manner which make code readble for others

**Comment by nandu-99** [comment]
pls assign me this issue, i can arrange the files in a good structure, so that it will be easy for other contributors as well who all are working, ill resolve this issue as soon as you assign me

**Comment by Anishkagupta04** [comment]
You can 🫶

**Comment by nandu-99** [comment]
Please open this issue

**Comment by nandu-99** [comment]
@Anishkagupta04

**Comment by Anishkagupta04** [comment]
Reopened

**Comment by nandu-99** [comment]
thank you

**Comment by nandu-99** [comment]
@Anishkagupta04 please assign this issue to me
