### ISSUE TITLE
💡[FEATURE]:  Placing instagram, facebook and twitter in the footer instead in top bar.

### ISSUE THREAD

**Issue by meghana9044** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#132]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. (Generally, users tend to search for social media handles in the footer section but in this webiste they are placed in top bar)
.
**Describe the solution you'd like**
A clear and concise description of what you want to happen. (Placing the social media handle links in footer section beside copyrights statement).

**Describe alternatives you've considered**

**Additional context**

@Anishkagupta04 @varshith257 I'm interested in contributing to this project under GSSOC'24. Please assign this issue to me.

**Comment by varshith257** [comment]
@meghana9044 They are already present in the footer. Remove it from header it will bee fine

**Comment by meghana9044** [comment]
> @meghana9044 They are already present in the footer. Remove it from header it will bee fine

Sir, I removed it from header and committed

**Comment by meghana9044** [comment]
@varshith257 please add label "level1" , L should be in small letter for us to count this in leaderboard

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.
