### ISSUE TITLE
💡[FEATURE]: Adding a favicon to the website

### ISSUE THREAD

**Issue by sancharigandhi** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#133]
**Is your feature request related to a problem? Please describe.**
Favicon will provide a visual representation to the website. By adding a favicon, I will improve the site's visual identity and make it easier for users to recognize and navigate to the website among their bookmarks and browser tabs.

**Additional context**
![favicon](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/140971159/baed7099-aecb-4ca9-a587-7cb08bf7b240)

@Anishkagupta04 kindly assign me this issue under GSSoc 24, I would like to work on this issue.
Thank you!

**Comment by solanki505** [comment]
I would like to work on this issue under GSSOC'24
