### ISSUE TITLE
📝[Docs]: adding some more in readme file

### ISSUE THREAD

**Issue by RiyaaBhatt** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#134]
I would like to include the following in the README file and kindly assign this task to me as part of GSSoC'24 i have also generated pull request regarding this
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/128878008/f60e95dc-0994-4f1b-86f1-fae108dfcf72)
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/128878008/59a4769b-1bc4-4bdd-b283-ae491605e54a)

**Comment by varshith257** [comment]
@RiyaaBhatt Thanks for the idea. Here you go :)
