### ISSUE TITLE
💡[FEATURE]: Improve Navigation bar

### ISSUE THREAD

**Issue by Naincy04** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#138]
**Is your feature request related to a problem? Please describe.**

Improving the navigation bar :- 
Too many items make it look messy and not aligned properly
A simpler, organized navigation bar looks better and is easier to use.
Matching styles make the website look more professional.

**Additional context**

![Screenshot from 2024-05-15 19-14-40](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/111273192/5ccd9a20-5add-4cd0-b587-859b8af8ac24)

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the RAPIDOC Healthcare Website project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.

**Comment by anushkaaa34** [comment]
I'm would love to contribute to this project. it would be great if you could assign me this issue
here's my linkedIn profile https://www.linkedin.com/in/anushka-sinha-09606b267/

**Comment by ShahHetviIT** [comment]
sorry by mistake i clicked can u please assign me again

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.
