### ISSUE TITLE
Improving the UI of Make an Appointment section

### ISSUE THREAD

**Issue by Kriagr23** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#143]
Alignment of the appointment the section can also be improved input fields do not have the same colored text 
Kindly Assign this issue to me I can make the required changes 
thank you 
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/121168949/e1413da5-5435-4adc-9d00-c1da9549b0f2)

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.
