### ISSUE TITLE
💡[FEATURE]: Add Chatbot to Enhance User Interaction

### ISSUE THREAD

**Issue by Vaibhav22p-qw** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#146]
A doctor-like chatbot provides medical advice and information by simulating conversations with a healthcare professional. It can answer common health queries, offer guidance on symptoms, suggest possible treatments, and advise when to seek medical attention. The chatbot uses natural language processing to understand user inputs and provide accurate, relevant responses, ensuring a helpful and engaging user experience.

ASSIGN ME (Under GSSoC'24)

**Comment by Vaibhav22p-qw** [comment]
Hello @varshith257 & @Anishkagupta04 Please assign me this project to get best user experience in chat bot 
the only thing you have suggest that what is name of chat bot.

**Comment by Anishkagupta04** [comment]
Already assigned
