### ISSUE TITLE
💡[FEATURE]: Add a Customized Scrollbar to match the theme of the site.

### ISSUE THREAD

**Issue by Vimall03** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#148]
**Is your feature request related to a problem? Please describe.**
Currently, RapiDoc lacks a customized scrollbar that matches the overall theme, which affects the visual coherence and user experience.

**Describe the solution you'd like**
Integrate a customized scrollbar that harmonizes with the site's theme. This enhancement will not only improve aesthetics but also contribute to a seamless browsing experience.

kindly assign me this issue.

**Comment by Kriagr23** [comment]
@Vimall03 Hi! can you please assign me this issue under GSSoC'24

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@HimanshuNarware Sir, I would really like to work on this issue, so please assign it to me.
