### ISSUE TITLE
CONTRIBUTING.md Grammar changes are required in this file.

### ISSUE THREAD

**Issue by abhishekdumaniya** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#158]
CONTRIBUTING.md This file needs grammar changes.

**Comment by abhishekdumaniya** [comment]
I have worked on this. @varshith257, @Anishkagupta04 Can you assign me under GSSOC 24?

**Comment by Anishkagupta04** [comment]
Okay do that

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.
