### ISSUE TITLE
📝[Docs]: Adding the Project setup and how to run locally 

### ISSUE THREAD

**Issue by AbhiJay1287** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#162]
Adding the Project setup and how to run locally in system to the Documentation can provide a much more clear way of setting up the project and running it on the web browser 

I would like to add those steps even to provide better clarity for the contributors

@Anishkagupta04  @varshith257 Can you please assign it to me under GSSOC'24?

**Comment by Anishkagupta04** [comment]
Assigning
