### ISSUE TITLE
💡[FEATURE]: Improving the UI of home section

### ISSUE THREAD

**Issue by Manishar55** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#169]
Hii @Anishkagupta04 
The home page UI is not looking good The video playing in the background  is very large and not properly aligned  
and also the headings and download button are not aligned properly

I want to fix all these issue of home page to make it more beautiful 
Can you please assign this task to me under gssoc24

![Screenshot 2024-05-16 200326](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154615478/a922d058-8f80-486d-b745-2d53f7a1eaea)

**Comment by Anishkagupta04** [comment]
Assigning

**Comment by aryanmehra0** [comment]
@Anishkagupta04 hii i would like to handle this issue assign me this task

**Comment by Henin-6024** [comment]
I would like to contribute for this project. Please assign this task to me under GSSoC'24 with required labels.

**Comment by varshith257** [comment]
Home Page is good for now
