### ISSUE TITLE
💡[FEATURE]: Add Appointment page

### ISSUE THREAD

**Issue by bhumika-1127** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#170]
I wanted to add an appointment page for the button "make an appointment" under GSSOC'24. @Anishkagupta04 kindly assign me this task.
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/137604220/8a36eb32-f332-4092-a47a-de816374942e)

**Comment by bhumika-1127** [comment]
@varshith257 @Anishkagupta04 It's a humble request if you could kindly label it level3 as it took a lot of time and efforts to make it and also I have not only made the structure using HTML but also added styling and used Javascript to make it more dynamic. Hoping you will understand.

**Comment by varshith257** [comment]
Don't worry about it. We have policy of changing labels based on your PR work. Will change based on your PR :)

**Comment by bhumika-1127** [comment]
@varshith257 Regarding what updates are you asking sorry I didn't understand. Also I am busy in my exams right now, I will look into the matters once my exams get over. Kindly let me know, if I could help in any possible way.

**Comment by bhumika-1127** [comment]
okay i will look into it @varshith257

**Comment by bhumika-1127** [comment]
@Anishkagupta04 you want me to edit this page 
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/137604220/ebf80adf-6ab4-4355-9c0c-438f4bfe4277)
to something like this 
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/137604220/a6de574b-522a-466f-ab3d-226325f4b3a3)
Am I correct?
