### ISSUE TITLE
Correcting the Spelling Mistake

### ISSUE THREAD

**Issue by meghana9044** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#174]
I would like to contribute to this project by correcting the spelling mistake of medicines, Please assign this issue to me under GSSOC'24.
<img width="1376" alt="Screen Shot 2024-05-16 at 10 21 17 PM" src="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/105973009/2c042eaf-59b5-4ff1-8777-8c51cdab8aca">

**Comment by Anishkagupta04** [comment]
Assigning

**Comment by meghana9044** [comment]
> Assigning

Thank You

**Comment by Ananyarawa8t** [comment]
Hey @Anishkagupta04 ,
I would like to fix the Typos. Kindly assign this issue to me under GSSOC'24 label.
Best Regards,
Ananya Rawat

**Comment by yogita-github** [comment]
@Anishkagupta04 I would like to work on this issue kindly assign it to me.

**Comment by meghana9044** [comment]
> Assigning

@varshith257 Please assign.

**Comment by 143divya** [comment]
Please assign this to me
