### ISSUE TITLE
Adding the year near copyright symbol

### ISSUE THREAD

**Issue by meghana9044** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#175]
I would like to contribute to this issue by adding the year beside copyright symbol.
Please assign this issue to me under GSSOC'24.
<img width="1433" alt="Screen Shot 2024-05-16 at 10 22 35 PM" src="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/105973009/331c7363-4062-49cf-8819-e6ec7baadf88">

**Comment by meghana9044** [comment]
@varshith257 Can you please label the issue as level 1

**Comment by 143divya** [comment]
Please assign this to me

**Comment by meghana9044** [comment]
@varshith257 Please label this pr
