### ISSUE TITLE
🪲[Bug]: Enable Click-to-Redirect Functionality for Contact Information Links

### ISSUE THREAD

**Issue by MrPC7** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#181]
### Describe the bug
Contact information links (location, email, and phone number) do not redirect to the default app on the user's device when clicked. Instead, they are displayed as plain text without any interactivity.

### To Reproduce
1. Go to the contact section of the page.
2. Click on the email address: `rapidoc@mail.com`.
3. Click on the phone number: `+91 1234567890`.
4. Click on the address: `IGDTUW, Delhi`.
5. Observe that no default application (email client, phone dialer, or maps application) is opened.

### Expected Behavior
When the email address is clicked, it should open the default email client with a new message addressed to `rapidoc@mail.com`.
When the phone number is clicked, it should open the phone dialer with `+91 1234567890` pre-filled.
Clicking on the address should open the default maps application showing the location.

### Additional Context
Ensuring these links redirect to the appropriate default applications will enhance user experience by providing seamless interaction with contact information.

## Solution
Update the contact information links to use `mailto` for email, `tel` for phone number, and a Google Maps link for the address to ensure they open the appropriate default applications (email client, phone dialer, and maps application) on the user's device when clicked.

_Assign me this issue under **GSSOC24**_

**Comment by Anishkagupta04** [comment]
Assigning
