### ISSUE TITLE
💡[FEATURE]:A structured footer

### ISSUE THREAD

**Issue by P-lavanya16** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#186]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by somu545** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by Harsha19-08** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by P-lavanya16** [comment]
![Screenshot (87)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/145569662/8202cb78-f1cc-4c97-8b42-3274dd72c5b5)
