### ISSUE TITLE
🪲[Bug]: Header Section Not Responsive Across Devices; Video Overlaps with Header and Unusable Space

### ISSUE THREAD

**Issue by MrPC7** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#198]
### Description

**Describe the bug**
The header section is not responsive on all devices, leading to display issues. Additionally, there is overlapping between the video and the header, which affects the user interface and degrades the user experience. There is also some unusable space that unnecessarily takes up room, further impacting the layout and usability.

**To Reproduce**
1. Go to the homepage on a mobile device or resize the browser window to a smaller size.
2. Observe the header section for responsiveness issues.
3. Play the video.
4. Scroll down to where the video overlaps with the header.
5. Notice any unusable space that could be optimized.

**Expected behavior**
The header should be fully responsive and adjust to different screen sizes without layout issues. There should be no overlap between the video and the header, ensuring a clean and user-friendly interface. Additionally, the layout should be optimized to remove any unusable space, making the best use of available screen real estate.

**Screenshots**

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/91939963/4f2e13e4-09c2-47bd-9bfd-f8ef97e3cba5)

**Additional context**
This issue impacts the overall user experience, especially on mobile devices and smaller screens. Fixing this bug will enhance the site's usability and aesthetic appeal by ensuring a responsive design and optimizing space utilization.

## **Solution**
Implement responsive design techniques such as media queries to ensure the header adjusts correctly across all device sizes. Adjust the layout to prevent video overlap and eliminate any unusable space, enhancing the overall user experience and interface usability.

_Assign me this issue under **GSSoC'24**_

**Comment by mondalsurojit** [comment]
I hope this message finds you well. I am a participant in the GirlScript Summer of Code (GSSoC) and I am very interested in contributing to this project. Could you please assign me under GSSoC level-3 problem.

Fixing this bug is crucial as it impacts the overall user experience and asthetics of the website across devices. I am eager to contribute my skills to resolving this issue promptly.

Thank you for considering my request.

Best regards,
Surojit Mondal

**Comment by MrPC7** [comment]
@Anishkagupta04 @varshith257

**Comment by gudia18** [comment]
i will work on this
