### ISSUE TITLE
🪲[Bug]: Featured and About Us Sections Not Responsive; Poor Aesthetics and Usability – UI/UX Improvement Needed

### ISSUE THREAD

**Issue by MrPC7** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#199]
### Description

**Describe the bug**
The Featured section and About Us section are not responsive on all devices, resulting in poor display and usability. These sections do not look visually appealing and are difficult to use, negatively impacting the overall user experience.

**To Reproduce**
1. Navigate to the homepage on a mobile device or resize the browser window to a smaller size.
2. Scroll to the Featured section.
3. Observe the responsiveness and visual appearance of the Featured section.
4. Scroll further to the About Us section.
5. Observe the responsiveness and visual appearance of the About Us section.

**Expected behavior**
Both the Featured and About Us sections should be fully responsive, adjusting properly to different screen sizes. They should be visually appealing and easy to use, providing a seamless user experience.

**Screenshots**

Below shown Image is the Screenshot of Feature section, it is not user friendly and even text is not visible.
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/91939963/f3b6a725-6506-4e62-8f63-aedcee9c2938)

See the alignment of the about section it is not user friendly.
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/91939963/470e7379-9202-48d3-b327-725811521355)

**Additional context**
Improving the responsiveness, aesthetics, and usability of these sections will significantly enhance the user experience across all devices. Ensuring these sections are well-designed and functional is crucial for maintaining user engagement and satisfaction.

## **Solution**
Apply responsive design techniques such as media queries and flexible grid layouts to ensure the Featured and About Us sections adjust properly across all devices. Enhance the visual design and usability of these sections to create a more appealing and user-friendly interface.

_Assign me this issue under **GSsoc24**_

**Comment by mondalsurojit** [comment]
I hope this message finds you well. I am a participant in the GirlScript Summer of Code (GSSoC) and I am very interested in contributing to this project. Could you please assign me under GSSoC level-3 problem.

Fixing this bug is crucial as it impacts the overall user experience and asthetics of the website across devices. I am eager to contribute my skills to resolving this issue promptly.

Thank you for considering my request.

Best regards,
Surojit Mondal

**Comment by MrPC7** [comment]
@Anishkagupta04 & @varshith257 please do assign and add labels, so that I can start working on this issue

**Comment by MrPC7** [comment]
@Anishkagupta04 @varshith257
