### ISSUE TITLE
Successfull Appointment

### ISSUE THREAD

**Issue by CS251000** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#20]
A new web page can be created which is redirected to after filling the appointment form.
This will ensure the user that the form is submitted without any ambuguity

Kindly assign this to me under GSSOC contribution

**Comment by Pratik2401** [comment]
Excited to get started on GSSoC 24, assigning me an issue would be awesome

**Comment by Anishkagupta04** [comment]
Proceed 👍

**Comment by CS251000** [comment]
@Anishkagupta04 kindly assign this issue to me and add a level and gssoc label on this please

**Comment by CS251000** [comment]
@Anishkagupta04 kindly add labels so that i can contribute under gssoc

**Comment by varshith257** [comment]
@CS251000 Assigned!
