### ISSUE TITLE
💡[FEATURE]: Add Support for Netlify Deployment

### ISSUE THREAD

**Issue by asr2003** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#207]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I push new commits to our project repository and need to manually deploy updates to see the live changes. It disrupts the workflow and makes it harder to quickly share live updates with Project Admin and reviewers.

**Describe the solution you'd like**

I would like to integrate Netlify deployment into the project so that every commit automatically triggers a build and live deployment. This way, every commit will result in a live, up-to-date version of the project that can be easily accessed and reviewed.

**Describe alternatives you've considered**

1. Manual Deployment: Manually deploying the project after each commit. This is time-consuming and inefficient.
2. Other Hosting Services: Using other hosting services like GitHub Pages or Vercel, but Netlify offers specific features and ease of use that are highly beneficial for our workflow.
3. Local Preview: Running a local server to preview changes, which doesn't provide a sharable live link for remote team members or stakeholders.

**Additional context**

Integrating Netlify will streamline our development process by providing continuous deployment and immediate live previews for every commit. This will enhance collaboration, improve the feedback loop, and ensure that our project is always up-to-date and accessible online.

More information: 

- Deployment steps  https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/
-  Netlify live deployment Workflow https://github.com/knative/docs/blob/main/.github/workflows/knative-nightly-site-build.yaml

Once deployment is done by maintainer and I'd like to work on integrating workflow for live deployment for each commit

**Comment by varshith257** [comment]
@asr2003 Thanks for this feature idea. It's really helpful to streamline reviewing process

**Comment by varshith257** [comment]
@Anishkagupta04 It would be great if you could work on deploying. 

Deployment steps:

-  https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/

**Comment by Anishkagupta04** [comment]
Okay will do @varshith257

**Comment by 143divya** [comment]
Can you please assign this task to me.?

**Comment by varshith257** [comment]
@143divya Thanks for your enthusiasm to work with us. But this is the work to be done by PA

**Comment by 143divya** [comment]
Okay
