### ISSUE TITLE
The UI of the footer doesn't look good

### ISSUE THREAD

**Issue by abhishekdumaniya** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#217]
The footer UI doesn't look good I want to improve the footer UI I have worked on this. @varshith257 and @Anishkagupta04 Can you assign me under GSSOC 24?

![Screenshot 2024-05-19 005116](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/123349721/97c34e55-f2b7-4d82-b731-28dfa70ce120)

**Comment by Yuvraj960** [comment]
@varshith257 Please assign this issue to me under GSSoC24. I did like to work on this issue

**Comment by abhishekdumaniya** [comment]
> @abhishekdumaniya You have active 3 issues assigned. Please work on them and its program to give everyone a chance to contribute. Let's give this issue to others who are willing to work
> 
> Thanks for active contributor in our project

Work has already been done on this so I have closed this issue

**Comment by Priyanka-Ray-Choudhury** [comment]
Hello @Anishkagupta04 ....My name is Priyanka Ray Choudhury, Can you please assign this task to me under the gssoc tag?
