### ISSUE TITLE
Addd social media and feedback section in blog page 

### ISSUE THREAD

**Issue by rajlaxmi03** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#22]
Addd social media and feedback section in blog page

**Comment by Mrigaank-9** [comment]
Hello, I trust this message finds you well. I'm writing to express my eagerness to contribute by adding a Social Media and feedback section to this platform. I believe this addition will not only enhance user engagement but also provide valuable insights for improvement. I'm excited to make this section visually appealing and user-friendly. Could you please assign me this task? I'm looking forward to the opportunity to contribute further.

**Comment by Pratik2401** [comment]
Ready to roll for GSSoC 24, assigning me an issue would be fantastic

**Comment by richasriva** [comment]
I can fix this issue properly. Kindly assign this issue to me.

**Comment by Anishkagupta04** [comment]
@richasriva proceed

**Comment by richasriva** [comment]
Okay, @Anishkagupta04, Thankyou for assigning.

**Comment by richasriva** [comment]
@Anishkagupta04 I am little bit confused that where to merge blog section, in the main page or create a new html page for blog and feedback system? Kindly Confirm.

**Comment by rajlaxmi03** [comment]
In the main page

**Comment by richasriva** [comment]
@rajlaxmi03 Okay

**Comment by richasriva** [comment]
Hi, @Anishkagupta04 I have solved this issue, kindly check PR #59 for the same.

**Comment by varshith257** [comment]
@rajlaxmi03 Thanks for suggestion. After raising an issue next time, ask to assign the issue. So that we will get clear and assign you. Sorry for the miscommunication had here
