### ISSUE TITLE
🪲[Bug]:Improper Alignments of Navbar items such as Home Page, About Page, and Services Section

### ISSUE THREAD

**Issue by Annapurna0311** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#228]
**Describe the bug**
There are presence of improper Alignments of Navbar items such as Home Page, Contact Page, and Services Section

**To Reproduce**
1. Run the index.html on local host server.
2. Scroll down or navigate through each of the section in the navbar.

**Expected behavior**
For attractive and adaptive user interface the  flow of design must be constant & continuous. Moreover, proper alignments crafts the beauty of websites and must be kept in high priority before implementation. The sectional items must be proper indented to fit up the contents of the UI elements.

**Screenshots**
![Screenshot 2024-05-19 214812](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146976500/389b0926-b4f9-4462-ae0f-5f7f6e012b9a)
![Screenshot 2024-05-19 214822](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146976500/ed9becf7-0f0f-4327-b515-df6a69957ed6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 23H2

**Comment by Anishkagupta04** [comment]
Assigning

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Anishkagupta04
