### ISSUE TITLE
Enhancement [dark mode]

### ISSUE THREAD

**Issue by rajlaxmi03** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#23]

**Comment by Pratik2401** [comment]
Eager to make my mark on GSSoC 24, assigning me an issue would be fantastic!

**Comment by krish-san** [comment]
hello, I'd like to contribute to this issue. As someone who is experienced in the field of web development, I'm confident i could fix this issue asap. Please assign me on this issue under GSSoc'24

**Comment by TanishMoral11** [comment]
hey @Anishkagupta04 , kindly assign this issue to me...

**Comment by gargimukherjee25** [comment]
Hello @Anishkagupta04 , I am Gargi! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24. I have used it in one of my projects and can work on it.

**Comment by Anikketsingh** [comment]
went through the code , I simple fix to this issue , I can work on this pretty efficiently ! can you please assign this to me ?@anshikagupta04

**Comment by rajlaxmi03** [comment]
Hey this issue is raised by me I myself find it easy to do and I have worked on this before I would like to contribute to this

**Comment by Anishkagupta04** [comment]
@krish-san you can do this

**Comment by krish-san** [comment]
@Anishkagupta04 thankyou ! Can you please assign me so that I can give pull request

**Comment by varshith257** [comment]
@rajlaxmi03 Are you willing to work  on this?

**Comment by rajlaxmi03** [comment]
Yess i am working on this

**Comment by varshith257** [comment]
Isn't it the PR related of this issue ?
- https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/pull/97

**Comment by krish-san** [comment]
@varshith257 yes
