### ISSUE TITLE
🪲[Bug]: Unstructured Footer section and aligned along with the non-interactive feedback support section

### ISSUE THREAD

**Issue by Annapurna0311** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#231]
**Describe the bug**
Footer is unresponsive plus feedback form submission.

**To Reproduce**
1. Go to website
2. Scroll down to footer section and feedback form above that.
**Expected behavior**

**Screenshots**
![Screenshot 2024-05-19 214849](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146976500/22772aa0-ac7f-4ecf-b1b0-6afe29f3021b)

**Comment by Anishkagupta04** [comment]
Assigning

**Comment by elikases** [comment]
What is the URL of the website?

**Comment by himadeepthi1** [comment]
@Anishkagupta04 , I would like to work on this issue , can you assign this to me
