### ISSUE TITLE
🪲[Bug]: Updating the "Nearest Lab" Logo in Statistics

### ISSUE THREAD

**Issue by Kiran-pande-30** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#234]
**Describe the bug**
A suggestion to change the "Nearest Lab" logo.

**To Reproduce**
1. Go to RapidDocs
2. Scroll down to statistics section

**Expected behavior**
A "Flask/Beaker" would be more related to the "Nearesr Labs".

**Screenshots**
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/105718863/4558774b-5fba-47e1-96aa-c5b751ff235f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome

**Comment by Priyanka-Ray-Choudhury** [comment]
Hello @Anishkagupta04 ....My name is Priyanka Ray Choudhury, Can you please assign this task to me under the gssoc tag?
