### ISSUE TITLE
🪲[Bug]: Smaller screens

### ISSUE THREAD

**Issue by sharmi4590** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#242]
**Describe the bug**
The page when for smaller dimensions the side scroller is being his and all other make the spot. I will make sure to align it properly.

**Screenshots**
![Screenshot_20240520-232241](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/102676949/64580951-88f7-4b9a-bb42-f94737492ccb)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Anishkagupta04** [comment]
Assigning

**Comment by Sakshi-gupta66** [comment]
Please assign it to me.
