### ISSUE TITLE
💡[FEATURE]: Add back to top button

### ISSUE THREAD

**Issue by Saimanjari777** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#253]
**Is your feature request related to a problem? Please describe.**
The back to top button is missing which makes the users to navigate easily through the website.

**Describe the solution you'd like**
I would like to add the back to top smooth transition button which helps to get to the top of the website.

**Additional context**
I am working under GSSoC'24
Please assign this issue to me!

**Comment by ParthNakum21** [comment]
Hello @Anishkagupta04 , I'm interested in contributing to the project by implementing functionality of back to top button. Could you please assign this task to me with label and level? I am working under GSSoC'24.
