### ISSUE TITLE
The hero section is not aligned properly. I'd like to contribute to the alignment of the hero section. Please assign this task to me

### ISSUE THREAD

**Issue by raniafarooq** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#27]
<img width="944" alt="Screenshot 2024-05-10 211101" src="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/95012734/a1ed5080-b62c-4b0c-af72-6880c8b8f44f">

**Comment by r7projects-shayan** [comment]
Hey @Anishkagupta04 I can completely fix the horizontal overflow in the hero section and make it right. Kindly assign this task to me
