### ISSUE TITLE
🐞[Bug]: Improper alignment 

### ISSUE THREAD

**Issue by kesharwaniyanshi** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Improper alignment which does not make the website look good.

### Expected behavior

Here the Alignment should be adjusted so that website looks better.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/123561974/d583f12b-4438-46f8-a10a-fab6c8c4b471)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by HareRamDwivedi** [comment]
Hey, please assign me this issue under GSSoC 2024.

**Comment by harshcodesit** [comment]
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the UI in an interactive manner, making it visually appealing.

Please assign this task to me, GSSOC'24 .
