### ISSUE TITLE
CONTRIBUTING.md file missing.

### ISSUE THREAD

**Issue by Pranjalll01** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#28]
Hey  @Anishkagupta04 ,
 Pranjal here Contributor @GSSoC'24
repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

could you assign this to me ?

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by Anishkagupta04** [comment]
@suhanipaliwal you can do 
if you don't mind to work with @Pranjalll01 you both together can do

**Comment by suhanipaliwal** [comment]
I can work with @Pranjalll01 on this issue. Please assign this issue to me as well. Also, please add the labels of GSSOC'24 and the label of appropriate level (like level 1, 2 or 3) on this issue.

**Comment by Pranjalll01** [comment]
Sure @Anishkagupta04 ,
We don't have any issue.
