### ISSUE TITLE
[BUG]: Social media icons not containing the valid link , or not working

### ISSUE THREAD

**Issue by SougataXdev** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#30]
i will add all the links to all the icons , which is going to improve user experience

**Comment by SougataXdev** [comment]
@Anishkagupta04 please assign this task to me

**Comment by gargimukherjee25** [comment]
Hello @Anishkagupta04  I am Gargi! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by ramankumar7c** [comment]
Hello @Anishkagupta04 , I can fix the issue of social media links not working. I would appreciate if I am assigned this issue for GSSoC'24.

**Comment by Anikketsingh** [comment]
This is a very simple fix as i have already went through the documents and code , lemme work on this , assign it to me @Anishkagupta04

**Comment by ShatakshiPalli** [comment]
I would like to work on this issue and make sure that the social media icons work in the desired manner.
Please Assign me this issue.

**Comment by varshith257** [comment]
@SougataXdev Thanks for raising an issue. Closing as it is a duplicate of 
- #29
