### ISSUE TITLE
Adding the Responsive ness to the Whole website

### ISSUE THREAD

**Issue by suraj-9849** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This website is not perfect for the mobile user So I would like to work on this issue and solve it. So this the mobile users can also use this website so Please assign this to me under @gssoc @Anishkagupta04 

### Use Case

This can help the mobile user to also use this webiste

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146669517/f8f54a6f-4a52-4451-b8b8-9bc2e37faf2a)
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146669517/ff99c972-05c3-4a1a-b933-a64094e69ca7)
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146669517/832a2cac-60a5-4bd4-90cc-e2396b955e0d)
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146669517/30a05788-a6ed-40b8-9a37-f1d64153a00c)
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146669517/8636c4b5-79de-4868-bd06-60dbbbcebc47)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
Assigning

**Comment by suraj-9849** [comment]
Before:
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146669517/d508f1e0-9ac0-4f97-8308-a312b31a6413

Before Responsive:
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146669517/73a862a5-f164-44b2-ad7f-2ed50843459f

After & Responsive:
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146669517/7a082477-e1aa-47d3-bedf-6e74797e161b
 

I also solved the issues of :
#311 
#309 
#312 

If this results are ok Then I will make the PR @Anishkagupta04

**Comment by suraj-9849** [comment]
@Anishkagupta04 Reply mam????

**Comment by suraj-9849** [comment]
@Anishkagupta04 Reply mam please??
