### ISSUE TITLE
Improving the Access your medical records section

### ISSUE THREAD

**Issue by suraj-9849** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

So on exploring this website I saw that there is no proper allignment and no style for this section So I would like to work on this issue please assign this to me under @gssoc @Anishkagupta04 

### Use Case

It is not perfect and it doesn't suits I will be improving this section

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146669517/a138ead6-6ddb-4ea0-808e-16a94183f68b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
