### ISSUE TITLE
Improving the Doctors section

### ISSUE THREAD

**Issue by suraj-9849** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

on exploring this website I saw that the Doctor section is not perfect it is not perfect. So I would like to work on this issue please assign this to me under @gssoc @Anishkagupta04 

### Use Case

This can help the best user experience for the user 

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146669517/ae657b52-8de2-47e5-aee1-5dd16a552b4e)
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146669517/1be07d9e-3369-42c6-8b49-0fc9d1bdc987)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning

**Comment by suraj-9849** [comment]
@Anishkagupta04  mam the main issue here is the images mam some of them are portrait and some of them are landscape if u permit me then I will Change and images and work on it

**Comment by DhruvJohri** [comment]
please assign this issue to me @Anishkagupta04
