### ISSUE TITLE
✨[Feature Request]:  Improving the Feedback section

### ISSUE THREAD

**Issue by suraj-9849** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

On exploring this website I saw that the color and the backgeound and the allignment of the text are not perfect for this feedback section So I would like to work on this issue under @gssoc @Anishkagupta04 

### Use Case

This helps the best user experience while giving the feedback 

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146669517/383b209f-a31f-4a22-9c1a-d61f9aac06cc)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
