### ISSUE TITLE
Switch between Light mode and Dark Mode

### ISSUE THREAD

**Issue by ramankumar7c** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#32]
I want to add a toggle so that user can switch between light mode and dark mode. @Anishkagupta04  , kindly assign this issue to me for GSSoc'24.

**Comment by Anikketsingh** [comment]
went through the code , I simple fix to this issue , I can work on this pretty efficiently ! can you please assign this to me ?
