### ISSUE TITLE
🐞[Bug]: no logo in contact form page 

### ISSUE THREAD

**Issue by Devansh1508** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Logo is not visible in contact form page navbar.

### Expected behavior

there should be a logo at top left corner of navbar.

### Add ScreenShots

<img width="1078" alt="image" src="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/160311808/bd2d9443-aca6-4d72-a9f6-d6e4458e8c74">

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
Assigning

**Comment by Tarungupta18** [comment]
assign me
