### ISSUE TITLE
Add Dynamic Changes to Contributors in README.md

### ISSUE THREAD

**Issue by varshith257** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#324]
### Issue Description

Current README.md only shows the static image of contributions made by contributors. It needs to be automatically updated as contributions of contributors are made.

### Suggested Change

The changes need to be look something like this:

```
<a href="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/graphs/contributors">
  <img src="https://contributors-img.web.app/image?repo=Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-" />
</a>
```

The above code o/p would be:

<a href="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/graphs/contributors">
  <img src="https://contributors-img.web.app/image?repo=Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-" />
</a>

### Urgency

Medium

**Comment by Rishikesh63** [comment]
@varshith257  i would like to work on it ,could you  please assign me

**Comment by Rishikesh63** [comment]
@varshith257  for this issue i can create a new GitHub Action workflow file .github/workflows/update-contributors.yml
that will run on every push or pull request merge to the main branch, adding the contributor and updating the README.md file automatically.OR
I can write a custom script that interacts with the GitHub API to fetch contributors and update your README.md.
could you you please  assign me

**Comment by varshith257** [comment]
@Rishikesh63 I think we don't need to go for complexity. Refer to above suggested changes in the issue. It works fine
