### ISSUE TITLE
✨[Feature Request]: Emergence button is not visible in responsive mode

### ISSUE THREAD

**Issue by TARUN2K3** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When accessing the application in responsive mode, the Emergence button is not visible. This issue affects user experience on mobile devices and smaller screens.
## Steps to Reproduce
1. Open the application in a web browser.
2. Resize the browser window to a smaller width or use the browser's responsive design mode to simulate a mobile device.
3. Observe that the Emergence button is not visible.

### Use Case

The Emergence button should be visible and accessible in responsive mode to ensure usability on all screen sizes.

### Benefits

**Increased Accessibility**
  - Complies with accessibility best practices by making all features available to users with disabilities who might rely on responsive design features or use assistive technologies.
  - Mobile and tablet users constitute a significant portion of web traffic. By making the Emergence button visible in responsive mode, the application becomes more accessible to this demographic, potentially increasing user engagement and retention.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/127468524/bc2bb381-fe6d-4720-a5e1-ee61f958b87c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
