### ISSUE TITLE
✨[Feature Request]: Improve the layout of ' Featured Services Section'

### ISSUE THREAD

**Issue by Pruthaa17** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The featured services section takes up to much space which is unnecessary and can be avoided . Every feature is placed vertically , it can be placed horizontally .

### Use Case

It can make the landing page more navigable. 

### Add ScreenShots

Before : 
![Screenshot (347)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/7124f901-189a-482e-892c-88d7a5e992aa)
![Screenshot (348)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/243048fa-d1af-4b33-9b85-8d9420e6dff6)

After : 
![Screenshot (349)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/3ac708aa-cbca-410e-8954-2fe57c2001cf)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
the length and breadth of each box is different align please maintain it uniform

**Comment by Pruthaa17** [comment]
![Screenshot (350)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/92dc6ad2-8035-4db8-86a5-7c51ccb2a3c9)
is it satisfactory ?

**Comment by Anishkagupta04** [comment]
Yeah better

**Comment by Pruthaa17** [comment]
Can you assign this task and add labels so that i can create pull request !

**Comment by Anishkagupta04** [comment]
assigning
