### ISSUE TITLE
[IMPROVEMENT]: README can be improved

### ISSUE THREAD

**Issue by Dishika18** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#34]
Readme can be improved and can be more informative for the developers to understand about the project.
I can make it more informative and easy to understand about the project.
Kindly assign me this issue under GsSoc'24 contributor.

**Comment by anythingkartik** [comment]
Yeah thats what I thought @Dishika18 
It can be more simple and easy to understand 

 @Anishkagupta04 Please assign this task to to either her or both of us .

**Comment by Anishkagupta04** [comment]
both of you can worth together

**Comment by anythingkartik** [comment]
@Dishika18 Damn so quick
