### ISSUE TITLE
🐞[Bug]:  Enhancing the alignment and UI of footer section

### ISSUE THREAD

**Issue by Adv1919** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The footer section can be enhanced by adding proper alignment and hover effects. Also some more useful links can be added.

### Expected behavior

It will look more user appealing after the fixing

### Add ScreenShots

![Screenshot (118)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146080896/0d09261b-694e-4832-aa73-1934eea9f92f)

### What browsers are you seeing the problem on?

Safari, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
Pull the latest upstream. Footer has been restructured
