### ISSUE TITLE
✨[Feature Request]: No hover effect on contact

### ISSUE THREAD

**Issue by Shreyaa173** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

there is no hover effect on contact option

### Use Case

By adding hover effect

### Add ScreenShots

![Screenshot 2024-05-28 145414](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/144673309/45e0c8fe-e69f-466b-abb6-10c31184e090)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
Assigning
