### ISSUE TITLE
✨[Feature Request]: Add Hover Effect for better experince

### ISSUE THREAD

**Issue by zalabhavy** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add hover effects on cards under about.

### Use Case

It gives better user experince.

### Benefits

It gives better user experince.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/126322584/b51a4e8f-cba8-41b3-ac8d-00dc448125e1)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by HimangshuRanjan** [comment]
@Anishkagupta04, I would like to fix this issue. Please do assign me this under GSSOC'24.

**Comment by varshith257** [comment]
@zalabhavy Are you wiling to solve this issue?

**Comment by zalabhavy** [comment]
@varshith257  Yes i will do it.

**Comment by zalabhavy** [comment]
@varshith257 I have added PR please check it and merge !
