### ISSUE TITLE
✨[Feature Request]: Enhancement of Contact Section

### ISSUE THREAD

**Issue by diyashah28** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Horizontally align the elements of the section. Avoid repetition of same details in contact section e.g. 'Location' is repeated twice. 
Addition of labels to the input text fields. Make the form more compact.

### Use Case

Better readability of the contact section. Reduction of length and efficient utilization of the space on the webpage.

### Add ScreenShots

![Screenshot 2024-05-28 175417](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/145260436/d057297f-841a-4818-9f97-7947e598c0ac)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by diyashah28** [comment]
@Anishkagupta04 please assign me this issue under GSSOC'24.

**Comment by Anishkagupta04** [comment]
Didn't liked
