### ISSUE TITLE
🐞[Bug]: improve the PR comment workflow text:

### ISSUE THREAD

**Issue by Anshika14528** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Wants to improve the welcome text of pr comment  to get more engaging and polished message  commented when a pr is created.

### Expected behavior

To get  more engaging and polished welcome message for a pull request (PR) comment:

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@Anshika14528 Thanks for opening!

FYI, If you have opened issues, please tag @me or @Anishkagupta04 to get it assigned to you

**Comment by Anshika14528** [comment]
ok
