### ISSUE TITLE
✨[Feature Request]: Counts Section is not a properly aligned 

### ISSUE THREAD

**Issue by Pruthaa17** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The width is not proper 

![Screenshot (361)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/cebf7e6c-4c43-45ae-a571-effa8556d187)

It can fixed 

![Screenshot (362)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/df9741e4-3b7a-4e57-bcdf-c08718e42b13)

### Use Case

It will lead to better layout 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Pruthaa17** [comment]
1. Aligned sections : 

1. counts 
2. featured

2.Also made them Made responsive 

**### _EARLIER :_** 

![Screenshot (397)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/ba7b1db4-5c66-4ad2-a957-41290bfe9110)
![Screenshot (398)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/1d2ab87b-5811-4d22-a045-c4312a6a7fa1)
![Screenshot (399)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/0b7ed44a-d4ec-4549-999c-9635de68a660)
![Screenshot (400)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/e614a7a5-d1fc-43b7-bf56-b208754b588b)
![Screenshot (401)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/5e8aa0f1-6734-4094-8873-bdc5fe5279d0)
![Screenshot (402)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/1fc256af-ab40-43f7-b59e-b4e73bd288b0)


### **_AFTER MAKING CHANGES_** 

![Screenshot (405)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/d91be11a-caec-402b-8e30-1da2128d4cca)
![Screenshot (406)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/72439178-7bdc-47f0-b955-46635a982dca)
![Screenshot (407)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/1da1b089-f569-41c0-96ae-641377a4515a)
![Screenshot (408)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/141839876/ae4d89aa-1878-48b5-84bc-a8f762ac6970)

**Comment by Pruthaa17** [comment]
please assign level @varshith257

**Comment by varshith257** [comment]
Will add based on PR
