### ISSUE TITLE
✨[Feature Request]: Blood Test Page 

### ISSUE THREAD

**Issue by samarsajad** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The blood test icon leads to the homepage and has not been built. Features such as, type of test, method of choosing collection of the sample, available slots, pricing, etc would be added.

### Use Case

Adding detailed features to the blood test section, such as type of test, sample collection method, available slots, and pricing, enhances user experience by providing clarity, flexibility, efficient scheduling, and transparent pricing. This empowers users to make informed decisions, save time, and trust the service, leading to higher satisfaction and convenience.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by samarsajad** [comment]
Mam, please assign this to me @Anishkagupta04

**Comment by varshith257** [comment]
@samarsajad Can you provide a layout here about what you are planning? 

cc: @Anishkagupta04

**Comment by samarsajad** [comment]
Yeah sure, I am thinking of putting all these things on the blood test page
1. Test Categories
2. Search and Filter Options
3.Booking and Scheduling
4.Sample Collection Method
5. Pricing Information
6. Preparation Instructions
@varshith257 @Anishkagupta04

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL

**Comment by samarsajad** [comment]
@Anishkagupta04  @varshith257  can u please assign this to me?
