### ISSUE TITLE
✨[Feature Request]: In appoint a doctor page, clicking on the logo should direct you to home.

### ISSUE THREAD

**Issue by ayush-848** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the appoint doctor page there is no way to return to home page.
I want to make it in such a way that on clicking the logo user is directed to homepage.

### Use Case

I will help to exit from the 'Appoint' page to the home page

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/126975547/cd072399-4364-4e16-99e3-1ef599413cde)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@ayush-848 I think a issue exists which has to redirect to appointment page

**Comment by varshith257** [comment]
Someonee is working

**Comment by ayush-848** [comment]
@varshith257 is he/she going to add a cancel button, if that so then my issue also works fine.
Can you give me that issue number please???
Let me check if both of our idea collides

**Comment by varshith257** [comment]
I think it's 
- #263

**Comment by ayush-848** [comment]
@varshith257 His issue is related to the form and mine is "I want a user to get redirected to home" if he presses the logo "RapiDoc" from this "appoint" page

Our issues are different.

If you agree, you can assign my mentioned issue to me.

**Comment by ayush-848** [comment]
@Anishkagupta04 I have made the PR for this issue. Please check #392
