### ISSUE TITLE
Add a logo for RapidDoc

### ISSUE THREAD

**Issue by mohit2202solanki** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#39]

**Comment by mohit2202solanki** [comment]
hii @Anishkagupta04, 
Please assign this issue to me .

**Comment by Sailza** [comment]
hi @Anishkagupta04 Please assign this issue to me and also please mention label 1 for this issue

**Comment by anythingkartik** [comment]
Hey @Anishkagupta04 Please assign this to me and also add label to this issue else it would not count as a contribution to GSSoC

**Comment by anjali21a** [comment]
Hey @Anishkagupta04 i am interested to solve this issue, Please assign this to me.
 and you should also add label to this issue else it would not count as a contribution to GSSOC

**Comment by Arshavi-03** [comment]
Hello! @Anishkagupta04 ! I will be grateful if you please assign this to me!. I will do a great job doing this. Thank you.
The logo features a sleek, stylized depiction of a document being rapidly processed, symbolizing efficiency and speed. The design incorporates modern typography and clean lines to convey professionalism and technological advancement. The color scheme consists of vibrant blues and greens, suggesting trustworthiness, reliability, and growth. So, I will try to enhance the logo.

**Comment by Anishkagupta04** [comment]
@Arshavi-03 assigning

**Comment by anythingkartik** [comment]
If you haven't yet assigned, let me know

**Comment by Arshavi-03** [comment]
> @Arshavi-03 assigning

Thank you @Anishkagupta04 !! I will work on it.

**Comment by Arshavi-03** [comment]
> > @Arshavi-03 assigning
> 
> Thank you @Anishkagupta04 !! I will work on it.

My name is not in the assignees list yet. Can you please add my name? Thank you again @Anishkagupta04

**Comment by varshith257** [comment]
@mohit2202solanki @Sailza @anythingkartik @anjali21a @Arshavi-03 Could you share the image of the intended logo of the project here? It is an important feature to add. The best is selected and will be added to the project :)

**Comment by Arshavi-03** [comment]
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131901164/6437efac-7a3a-4170-8703-c3b6d383a7ae

**Comment by mohit2202solanki** [comment]
![logo](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/99522377/fd5d899c-58f9-4675-8db9-8489371cf84e)

**Comment by Arshavi-03** [comment]
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131901164/5b707ad8-c4d8-427a-a671-f486d59ab676

**Comment by anythingkartik** [comment]
> 
> https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131901164/6437efac-7a3a-4170-8703-c3b6d383a7ae
> 
> 

Did gou made that?

**Comment by AbhiJay1287** [comment]
@Anishkagupta04 @varshith257 I'm interested in contributing to this project by adding a beautiful logo. I have done 2 sample logos. I'm very good at canva. Please assign this issue to me under GSSOC'24.

![RAPIDO-5](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/105973197/e6274189-ddd0-4a0b-b5d6-d670042e6a48)
![RAPIDO-4](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/105973197/deeef7c8-5dcc-4332-b823-4294070bfd84)

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL

**Comment by Anishkagupta04** [comment]
@AbhiJay1287 The first logo you made is quite impressive

**Comment by Anishkagupta04** [comment]
What you say @varshith257 ?

**Comment by varshith257** [comment]
> What you say @varshith257 ?

Yes, let's go with it

**Comment by AbhiJay1287** [comment]
@Anishkagupta04 @varshith257 Thank you , Can you please assign this to me ?
I will add the logo to the website and make a pull request .

**Comment by varshith257** [comment]
@Arshavi-03 The logo you made in video and @AbhiJay1287  are really confused on Whose work is this.

The one who posted here is @Arshavi-03 . So assigned you

**Comment by AbhiJay1287** [comment]
They both are quite different sir , I have added the sethescope to the logo to enhance it 
![RAPIDO-5-2](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/105973197/5171cf16-842f-44c1-bfb1-ee36eab0e645)

**Comment by varshith257** [comment]
@Arshavi-03  Make some edit to your video logo of using the same above. We will add it in our website in a separate issue

**Comment by Arshavi-03** [comment]
> @Arshavi-03 Make some edit to your video logo of using the same above of @AbhiJay1287 . We will add it in our website in a separate issue

So do you mean I will have to animate the logo given by @AbhiJay1287 ? But then the quote underneath, should I add it too?

**Comment by Arshavi-03** [comment]
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131901164/dc25dc2b-b64a-4195-9299-218526f0e2bf

@varshith257 is it okay? Or do i need to change anything?

**Comment by varshith257** [comment]
@Arshavi-03  Make some edit to your video logo of using the same above. We will add it in our website in a separate issue

Use similiar colors of it in logo and text needs some improvement

**Comment by Arshavi-03** [comment]
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131901164/04af5675-eee4-49e7-960f-510d35b61e9b

@varshith257

**Comment by Arshavi-03** [comment]
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131901164/f1b69576-04e4-4e8e-9473-a6da79845c31

@varshith257

**Comment by Arshavi-03** [comment]
> @Arshavi-03 Make some edit to your video logo of using the same above. We will add it in our website in a separate issue
> 
> Use similiar colors of it in logo and text needs some improvement

Sir i made the video can you please tell me if it was alright or not for the new issue you mentioned?

**Comment by varshith257** [comment]
Create a new issue and will follow up there about your video progress
