### ISSUE TITLE
✨[Feature Request]:  Making Subscribe as button

### ISSUE THREAD

**Issue by MuraliDharan7** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The existing subscribe button at the footer is not a button, This should be a button,

### Use Case

This button make the users feel good rather than just clicking somewhere.

### Benefits

This button subscribe the website to get the updates faster and easier way and also may gives some offer according to the website.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/130668745/2fe03b55-e231-4de1-bf5c-d1653efe92ac)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by DrishtiRai777** [comment]
I would like to contribute to this aspect of the project. Please assign this issue to me under GSSOC 2024.
Thank you,
Drishti Rai
