### ISSUE TITLE
Emergency Button Text Disappears and Button Shrinks on Mobile View

### ISSUE THREAD

**Issue by Nithin9585** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#4]
When viewing the website on mobile devices, such as smartphones, the emergency button's text disappears, and the button itself becomes significantly smaller, potentially impacting its usability and visibility in critical situations. This inconsistency in the button's appearance could lead to user confusion and hinder the effectiveness of the emergency feature. To ensure accessibility and functionality across all device sizes, it's essential to address this issue by implementing responsive design techniques or adjusting the styling of the button for mobile views.

**Comment by Nithin9585** [comment]
I've raised an issue about the emergency button text disappearing on mobile view. I'd like to take care of this. please assign it to me?

**Comment by Anishkagupta04** [comment]
Okay proceed for this

**Comment by Shyambarua** [comment]
Assign this issue to me.
As a full Stack Developer and 1 Year experience I can Write optimized code and Make it responsive.
