### ISSUE TITLE
please add label for GSSoC24

### ISSUE THREAD

**Issue by lavshashank** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#40]
please add label for GSSoC24

_Originally posted by @lavshashank in https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/issues/38#issuecomment-2105669700_

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Please assign me this !

**Comment by Anishkagupta04** [comment]
@lavshashank assigning

**Comment by lavshashank** [comment]
Thank you I'll work in this issue.

**Comment by varshith257** [comment]
Will be adding it soon

**Comment by varshith257** [comment]
@lavshashank Added! Thanks for suggestions
