### ISSUE TITLE
📝[Documentation Update]: Modification of Readme.md file

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Modification of Readme.md file

### Suggested Change

By adding Gif emoji's and also alignment.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@varshith257

**Comment by varshith257** [comment]
What gifs and alignment you are planning to do?

**Comment by Anjaliavv51** [comment]
Their will be movement in emoji's and also according to make , I will change the font's and alignment.

**Comment by Anjaliavv51** [comment]
@varshith257 i want to add , a workflow , which allows a github user to automatically assign themselves and their is a condition that user can create only one issue at a time
