### ISSUE TITLE
✨[Feature Request]: Would u like to add translate button

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Translate button it like the users to read in their , mother language

### Use Case

Incase if anyone don't know english

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/ebf4596c-255f-497c-98cd-ce4f0d0f33c5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL

**Comment by Anjaliavv51** [comment]
@varshith257  any updates.
