### ISSUE TITLE
🐞[Bug]: Regarding the UI Elements 

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Regarding the UI Elements 
the UI elements are not style or aligned properly
according to issue #12

### Expected behavior

the UI elements are not style or aligned properly

### Add ScreenShots

check this
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/125277258/74b02675-4bec-44b0-bc58-84485c979bf9

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by RamakrushnaBiswal** [comment]
@Anishkagupta04 and @varshith257 i want to work upon it

**Comment by Anishkagupta04** [comment]
Assigning

**Comment by Rishikesh63** [comment]
i thought by changing css we can fix it @Anishkagupta04 can you please assign me

**Comment by RamakrushnaBiswal** [comment]
hy @Rishikesh63 i work on it
