### ISSUE TITLE
🐞[Documentation Bug]: missing learn.md 

### ISSUE THREAD

**Issue by deepak00944** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

missing learn.md file

### Expected behavior

there should be a clarity of project so we should add learn.md

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by deepak00944** [comment]
Hii @varshith257, Do you want me to add learn.md file?? Kindly assist me.

**Comment by varshith257** [comment]
Yes
