### ISSUE TITLE
Improve the UI/UX of the website

### ISSUE THREAD

**Issue by Sneha123-zudo** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to improve the UI/UX of the website.

### Use Case

<img width="674" alt="image" src="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/145490348/baef6264-2ca8-44a8-a891-e021e454efa9">

This particular section is not looking good i want to improve this .
Please assign me this issue under GSSOC'24

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@Sneha123-zudo Here you go
