### ISSUE TITLE
🐞[Bug]: Enhancing the News section UI

### ISSUE THREAD

**Issue by Adv1919** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The UI and alignment of the News section looks very plain and can be made more user appealing like the contact us section. The footer of the section can also be enhanced like the home page.

### Expected behavior

It can be made attractive with better layout and color coordination.

### Add ScreenShots

![Screenshot (124)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146080896/c2c8f67a-f01f-4312-8ed6-33f48dadb7ef)

### What browsers are you seeing the problem on?

Safari, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@varshith257 Here you go
