### ISSUE TITLE
🐞[Bug]:  Many sections overlapping in the Patient Portal Section

### ISSUE THREAD

**Issue by samarsajad** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Patient portal is overflown

### Expected behavior

Everything should be in place and visible

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142666229/b85c5b8d-b952-4ac0-abba-16f2370a6949)

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by samarsajad** [comment]
Please review this and assign this to me @Anishkagupta04

**Comment by Anishkagupta04** [comment]
Assigning
