### ISSUE TITLE
🐞[Bug]: Register button redirect to sign in page

### ISSUE THREAD

**Issue by samarsajad** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On clicking on the register button, the sign in/sign up portal opens up again

### Expected behavior

It should redirect to the main webpage

### Add ScreenShots

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142666229/c8844609-0f48-4bca-8404-c6c2750d6ef5

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by samarsajad** [comment]
Please assign this issue to me, ma'am @Anishkagupta04

**Comment by Anishkagupta04** [comment]
Assigning
