### ISSUE TITLE
🐞[bug]:Signup with google isn't working 

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#427]
![Screenshot_20240604_023622_Chrome.jpg](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/df96e6f6-16c9-4a99-bac2-307cea94a3f0)

Wanted to fix this.

**Comment by Anishkagupta04** [comment]
Assigning

**Comment by DiwareNamrata23** [comment]
I'm interested to solve this bug . I request @Anishkagupta04  to assign this issue to me .
thank you!

**Comment by Anjaliavv51** [comment]
@varshith257 i need a help

**Comment by Rishikesh63** [comment]
@Anishkagupta04  i wants to work on it  could you please assign me

**Comment by Rishikesh63** [comment]
@Anjaliavv51 could you please provide way by which i can reproduce this bug

**Comment by Anjaliavv51** [comment]
Sorry I didn't get u
