### ISSUE TITLE
✨[feature request]: Redesigning of Footer for Better User Experience 

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#428]
Toggle Share Button from this

![SmartSelect_20240604_024438_Chrome.jpg](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/06b5092f-2594-401c-9e27-4cc262788cb0)

To this

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/154777864/abbf18c9-2a23-4bcf-a50f-83788511dacc

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 @varshith257 , once checkout this feature.

**Comment by varshith257** [comment]
This is nice one to have

**Comment by Anjaliavv51** [comment]
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/2d301c80-d803-473d-ba20-8a2fef6449b9)


https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/6ce0f6da-ff6a-4882-ab3f-4ad2ab000e1d



@varshith257 @Anishkagupta04  please check is it okay

**Comment by varshith257** [comment]
It is good. Also, add the hover effect to the button and options and kept it under creating a new social media section in footer

**Comment by Anjaliavv51** [comment]
> It is good. Also, add the hover effect to the button and options and keep it under creating a new social media section in footer
> The above which is in video is the perfect one 

Can u make that place

**Comment by varshith257** [comment]
Add at left download corner of footer

**Comment by Anjaliavv51** [comment]
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/e572f2d7-e13c-4b5e-8abb-1af4fe0f4004)


@varshith257 now please check is it okay

**Comment by Anjaliavv51** [comment]
@varshith257 please mark the image

**Comment by Anjaliavv51** [comment]
> Better align this button at the down of the Quick Links section and  also add a hover effect as in the video you submitted as reference


If it is placed their , when it is toggled , some won't be visible so moved it to rught

**Comment by varshith257** [comment]
But maybe that could be the right place to place it IMO

**Comment by Anjaliavv51** [comment]
> But maybe that could be the right place to place it IMO

@varshith257 as your wish

**Comment by Anjaliavv51** [comment]
@varshith257 I will change the position

**Comment by Anjaliavv51** [comment]
@varshith257 

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/4b7920e6-33d1-47d7-8c5a-fbc459faf04b)


Now is it okay

**Comment by Anjaliavv51** [comment]
@varshith257 chatbox , share button and Signup with google all are modifed.
Have a look at the below screenrecording's.


https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/5e8847ac-c036-47eb-87a4-ef79d3b9958c


https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/a0d82f83-39dc-4315-8079-12c4a65f6805

**Comment by Anjaliavv51** [comment]
issue for Chatbot is #461 , if u assign me this issue , i will add the new Chatbot

**Comment by Anjaliavv51** [comment]
@varshith257  please check the below output is it okay?

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/46f8a68c-51c9-4abe-8103-d20b4fbead4a)

**Comment by varshith257** [comment]
@Anjaliavv51 Move follow us section align with Quick Link section and copyright to right corner of footer

**Comment by Anjaliavv51** [comment]
@varshith257

**Comment by varshith257** [comment]
Better redesign footer like this :

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/pull/459#issuecomment-2153748896

**Comment by Anjaliavv51** [comment]
@varshith257 okay

**Comment by Anjaliavv51** [comment]
@varshith257 now check is it okay

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/1ba6854e-0b6d-4f49-8b9a-9c24402078be)

**Comment by Anjaliavv51** [comment]
@varshith257 ?

**Comment by Anjaliavv51** [comment]
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/62f438a5-3651-4de2-9329-5949c38c39a0)

**Comment by varshith257** [comment]
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/117595548/456dc13c-b798-461f-909e-aaf778160dd8)
 

Align our footer with this

**Comment by Anjaliavv51** [comment]
@varshith257 now check 

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/58cc89cc-1f22-4c40-9529-1ed5bb6fa95e)

**Comment by Anjaliavv51** [comment]
@varshith257

**Comment by varshith257** [comment]
Done

**Comment by Anjaliavv51** [comment]
@varshith257 can I create PR now?

**Comment by varshith257** [comment]
Yes.
