### ISSUE TITLE
📝[Documentation Update]: Adding information on service cards

### ISSUE THREAD

**Issue by shruti110503** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The service cards show very less information. 
![Screenshot 2024-06-05 005011](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/118251562/279b5e86-c6d1-4958-a635-beeef9495c47)

### Suggested Change

I will add some more information on those so our customers get to know better.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
