### ISSUE TITLE
✨[Feature Request]: Enhance the About Section

### ISSUE THREAD

**Issue by Hemashree21** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#437]
### Is there an existing issue for this?
Issue #346 exists but I saw that there is already a merged pr so raising this again

- [X] I have searched the existing issues

### Feature Description

The current About section is not that visually appealing. I want to enhance this section. I will also make sure that it's responsive.

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/138188163/c78e24d1-cf13-4b3a-aba1-cb0438495351)

### Use Case

This section will give a brief overview about the different features of the website. Here is one of the template.

![Screenshot 2024-06-02 111143](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/138188163/fdbac3e3-6246-498f-b4f6-a620af7d70a1)

@Anishkagupta04 @varshith257  can you please assign this issue to me?

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
