### ISSUE TITLE
✨[Feature Request]: Adding an FAQ section

### ISSUE THREAD

**Issue by Hemashree21** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to work on adding an FAQ section to the website. I will make sure that the page is responsive as well.

### Use Case

The users might have so many questions in their mind so this section will be helpful. Here is one of the template.

![Screenshot 2024-06-01 124347](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/138188163/105dac3a-4384-4d26-bda1-aa10d071db88)

@Anishkagupta04 can you please assign this to me?

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
