### ISSUE TITLE
✨[Feature Request]: Adding Testimonial Section

### ISSUE THREAD

**Issue by Hemashree21** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to work on adding a Testimonial section. I will make sure that the section is responsive.

### Use Case

This section is important so that users can review the feedback of other users and gain a positive impression. Here is the template.

![Screenshot 2024-06-01 110647](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/138188163/06c30db3-d51d-4caf-9676-9c8c1e5fd3b4)

@Anishkagupta04 @varshith257 can you please assign this to me?

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
Provide a layout of the original website where you design in website

**Comment by Hemashree21** [comment]
> Provide a layout of the original website where you design in website

Means? I didn't get you sir

**Comment by varshith257** [comment]
@Hemashree21 Here you go!
