### ISSUE TITLE
Add chat Box

### ISSUE THREAD

**Issue by sidhigrover** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#44]
I will add chat box in Website
please assign me this under GSSOC 
@Anishkagupta04

**Comment by AmrutaZagade** [comment]
I am participating in GSSOC'24 and I am interested in this issue, Could you please assign me.

**Comment by Anishkagupta04** [comment]
@sidhigrover assigning

**Comment by hasmithagunda123** [comment]
Hey I m good at webdevelopment. Please assign me this issue

**Comment by sidhigrover** [comment]
@varshith257 
hello varshith

<img width="406" alt="Screenshot 2024-05-11 at 10 19 33 PM" src="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/123989540/ba9dd028-9109-48b8-94f3-e401f04effea">


decided to make chatbox like this.
if any person have any query related to any  website services  .he/she can ask their doubt in it.

**Comment by varshith257** [comment]
@Anishkagupta04  PTAL

**Comment by Anishkagupta04** [comment]
This is preety good @sidhigrover you can proceed making all the best 🫶

**Comment by sidhigrover** [comment]
Okay @Anishkagupta04 
Will start making it from 21 may✌🏻
Currently my final term college exams are going on 🥲

**Comment by Anishkagupta04** [comment]
No issue @sidhigrover

**Comment by sidhigrover** [comment]
@Anishkagupta04 I just saw today your website already have a chatbox.
should i add my chatbox?

**Comment by sidhigrover** [comment]
<img width="1440" alt="Screenshot 2024-05-30 at 6 21 07 PM" src="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/123989540/79f7f7b0-0edd-4939-a3bc-9c2c69b0b3dc">
I decided to make a chatbox like this which will work on predefined questions and answers

**Comment by varshith257** [comment]
Ok, looks good

**Comment by varshith257** [comment]
Make enhancements to the recent chatbot added

**Comment by varshith257** [comment]
Can you send ss of the chatbot present now in the project?

**Comment by sidhigrover** [comment]
<img width="1440" alt="Screenshot 2024-05-30 at 11 11 42 PM" src="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/123989540/205b16d4-442d-452a-8f2a-897eaf79cb96">
@varshith257

**Comment by varshith257** [comment]
Better change to your chatbot. Your's chatbot looking very good and visually appealing

**Comment by sidhigrover** [comment]
> Better change to your chatbot. Your's chatbot looking very good and visually appealing

okay
