### ISSUE TITLE
✨[Feature Request]: Adding error 404 page

### ISSUE THREAD

**Issue by taneeshaa15** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add error 404 page.

### Use Case

This feature will inform the user that an error has occured.

### Benefits

Informing the user about the error directly.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by taneeshaa15** [comment]
@varshith257 @Anishkagupta04 Please mention level also in the label.

**Comment by varshith257** [comment]
We will add it based on the PR work. We had misconceptions in the past between issue description and PR work. So we are following it

**Comment by taneeshaa15** [comment]
It's okay
Thankyou for clarifying.
