### ISSUE TITLE
🐞[Bug]: Content on the back ground

### ISSUE THREAD

**Issue by chaanakyaaM** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The content is flowing on the background on the home page.

### Expected behavior

The content should not outflow at the background.

It has to be like this :
![Screenshot (230)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131477601/515c8886-0093-4542-8862-23505dbad052)

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131477601/38560d35-43fb-498d-ae12-d87e0130c707)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SumithThota** [comment]
Please assign me this issue I would like to work on it under GSSOC'24 contributor

**Comment by DiwareNamrata23** [comment]
Hello I'm interested to work on this bug please assign this issue to me @varshith257
