### ISSUE TITLE
[BUG] : Responsive issue 

### ISSUE THREAD

**Issue by AnirbanGhosh2** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#45]
- In this project pages are not in proper Resposive mode.

- Please assign me this under GSSOC'24 I will solve and make proper responsive the home site.

- The body does not contains the hole screen.

- While opening the page in mobile it is not properly showing.

![4b](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/110912334/68f02810-1176-4c13-8b76-c372dd00d9ca)
![3b](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/110912334/e3346b64-86f7-4acf-9c32-d60be4b46ab9)
![2b](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/110912334/3eba869e-cd81-4bfb-83e8-a345cdb3da02)
![1b](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/110912334/d25a6441-2a4f-4795-bde6-3e522fa09a94)

Please assign this task to me under GSSOC'24 i will solve and add responsiveness to the page.

**Comment by AmrutaZagade** [comment]
I am participating in GSSOC'24 and I am interested in this issue, Could you please assign me.
