### ISSUE TITLE
🐞[Bug]: Letters not arranged properly on navbar

### ISSUE THREAD

**Issue by kanishk-2** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Patient portal is not properly aligned with other options

### Expected behavior

p is small in patient portal. so Making P capital as all other options initials are also capital.

### Add ScreenShots

<img width="700" alt="2" src="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/157130879/773c90ae-a342-49e7-aff7-89ae53ac64c4">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by kanishk-2** [comment]
@varshith257  can you add the level tag in this

**Comment by varshith257** [comment]
Will add based on your PR work
