### ISSUE TITLE
🐞[Bug]: Overlapping of Patient Portal and Contact us portion

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Patient Portal and Contact us portion overlapped.

### Expected behavior

The Box should be Arranged Properly . And also the content in it.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/7f3fe7d9-44bf-4b3a-8cdc-236cf5492867)

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/406aa4ca-2749-491c-bda2-00c03bf5c8f1)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@varshith257  @Anishkagupta04 please assign this issue.

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the RAPIDOC Healthcare Website project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.
