### ISSUE TITLE
✨[Feature Request]: Adding Animated icons in Footer and Navbar links

### ISSUE THREAD

**Issue by SadafKausar2025** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It will beautify the page after adding icons to it

### Use Case

.

### Add ScreenShots

![Screenshot (1939)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/137484958/f30c3d10-3220-4926-9604-2328f3b39187)

![Screenshot (1941)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/137484958/91b6e2d3-361f-4860-8ef4-a02e17bb125d)

![Screenshot (1942)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/137484958/06dc2939-c93b-4a74-84ae-f0e7a27c6625)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by geeta052** [comment]
hey @Anishkagupta04 please assign this issue to me?
