### ISSUE TITLE
📝[Documentation Update]: Making readme.txt file correctly

### ISSUE THREAD

**Issue by kanishk-2** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

there are 2 readme.txt files formed.

### Suggested Change

There should be 1 readme.txt file

### Rationale

There are 2 readme.txt files formed having 3-4 lines info in each.
so it's better to make 1 readme.txt file having the both file info together. 
Which will make better for searching ,reading and avoid confusion.

<img width="232" alt="readmetxt " src="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/157130879/9c51da36-51d8-4fbc-a107-447a5bee8113">

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by kanishk-2** [comment]
@varshith257 @Anishkagupta04 my pr was merged but I didn't received points bcz you have not added the level tag .
can you plz mention the level tag

**Comment by kanishk-2** [comment]
Can you add the level tag? As it's not been added

**Comment by varshith257** [comment]
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/117595548/b11e80a4-c679-4285-9260-90128d88b609)
