### ISSUE TITLE
✨[Feature Request]: To add a testimonial/review section

### ISSUE THREAD

**Issue by ayush-848** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a review/testimonial section where users and their review along with their photo will be displayed.

There will be right and left arrow to view the cards

### Use Case

It will help everyone to see the review of the website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ayush-848** [comment]
@varshith257 @Anishkagupta04 Please check, if you think this is required then kindly assign this task to me

**Comment by varshith257** [comment]
We already had a recent PR merged for testimonials
