### ISSUE TITLE
Patient Portal is again not aligned properly

### ISSUE THREAD

**Issue by samarsajad** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The content of the patient portal are going haywire

### Expected behavior

They should be well aligned and well placed with respect to each other

### Add ScreenShots

![Screenshot 2024-06-09 010435](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142666229/3f33de26-76a2-4291-ab22-3dfae597b4d3)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by samarsajad** [comment]
@varshith257 i had fixed it before but it seems like somebody has altered it again. Please review it and assign it to me. I also tried fixing the responsive of the section to see if it was a responsiveness issue but turns out it is not. And I request either on of you @Anishkagupta04  to please drop you linkedIn ID for easy communication

**Comment by varshith257** [comment]
We have slack for it and same I think you have connected with me in linkedin

**Comment by samarsajad** [comment]
> We have slack for it and same I think you have connected with me in linkedin

Can you please check the pull request #486
