### ISSUE TITLE
📝[Documentation Update]: static documentation site using mkdocs

### ISSUE THREAD

**Issue by Abhishek-Sood** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

currently there are a lot of .md files that are hectic to read for the people.

### Suggested Change

i want to propose to use a clear well structured static documentation site made using mkdocs that can be deployed in future
i ll set up mkdocs and use suitable theme for the site so that will be easy for the public to read from the site about the project rather than only .md files.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Abhishek-Sood** [comment]
@varshith257 sir if its not needed please tell not to :)

**Comment by varshith257** [comment]
It's needed and thanks for this idea
