### ISSUE TITLE
✨[Feature Request]:  Responsive Design

### ISSUE THREAD

**Issue by ishap11** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello, this is Isha Prajapati,
I hope you're doing well. I'm interested in improving our website's functionality and user experience 
I'd like to request the implementation of responsive design for our healthcare platform's website. This feature will ensure that the website adapts seamlessly to various screen sizes and devices, providing users with an optimal viewing and browsing experience.
 
I am eager to contribute under GSSoC'24 and help enhance our website’s functionality and user experience. Please assign this task to me.
Thank you!

### Use Case

Imagine a user accessing our healthcare platform from their mobile device. With responsive design in place, the website will adjust its layout and content to fit the smaller screen, making it easier for the user to navigate, read information, and interact with the platform's features.

### Benefits

Improved Accessibility: Responsive design will make our website accessible to users across a wide range of devices, including smartphones, tablets, and desktop computers.
Enhanced User Experience: Users will enjoy a consistent and user-friendly experience regardless of the device they're using, leading to higher engagement and satisfaction.
Increased Reach: With a responsive website, we can reach a broader audience and attract users who prefer to access the internet on mobile devices.

Implementing responsive design is crucial for ensuring that our healthcare platform is accessible and user-friendly for all users, regardless of the device they use to access it.

### Add ScreenShots

![Screenshot 2024-06-09 205816](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/128213933/9606791d-ebdc-4e88-ac2a-ef2d94ce7800)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Speedysays01** [comment]
Please assign this task to me. I will make sure the website looks good on mobile devices too.
