### ISSUE TITLE
🐞[Bug]: Colliding UI

### ISSUE THREAD

**Issue by vaishnavip27** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The cards in the section are colliding with the homepage because of what the homepage vertical slider is not getting viewed properly

### Expected behavior

I want to make the card layout a little bit shift to the downside because of which it won't collide with the homepage's vertical carousel

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/143169451/0733d026-a98d-439a-8e6a-957a48f88fdc)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by vaishnavip27** [comment]
@varshith257 Please assign me this issue

**Comment by varshith257** [comment]
@vaishnavip27 Here you go.

**Comment by DakshantJain** [comment]
Hello @varshith257 , I saw your complete website it delivers a great message and is beautifully designed. But as every art has some flaws, similarly your website do also have some of them... Here I can easily fix them and make them even good looking and functioning. I request you to assign this to me for one of the best results.

Thank You.
