### ISSUE TITLE
🐞[Bug]: Improvement in the styling of appointment page

### ISSUE THREAD

**Issue by DiwareNamrata23** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the page styling is not proper
<img width="692" alt="Screenshot 2024-06-10 at 6 49 46 PM" src="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142529986/ba2812ab-8b4c-4c01-9657-eecedd809be2">

### Expected behavior

addition of proper styling in the input box and giving proper animation to this page can be result in a good ui for appointment for the page

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Pavitra2128** [comment]
I want to edit that page and add styles to it
