### ISSUE TITLE
🐞[Bug]: Bugs in style.css

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Bugs in Style css

### Expected behavior

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/73ccdbb3-b618-4c09-a6db-656ca8d44eb3)

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/6e1ed5fb-6049-4d21-a04a-fc56519d3e4b)

### Add ScreenShots of Bugs

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/be38cde7-fcfc-4349-84b7-65bc843636d1)

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/9c42e50d-4b4e-42da-9815-1b477a36e6a5)

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/4a4f550d-bbd8-471b-b10a-d47462535f36)

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/383b1fe7-c7de-4a69-8c11-724206c72baf)

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/8d6836c6-16c7-49f7-b6b2-2e0b06a4029d)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Vibha17** [comment]
Hi I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

**Comment by Anjaliavv51** [comment]
@Vibha17 Gupta it is already solved , review is balanced.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR #517
