### ISSUE TITLE
🐞[Bug]: logo in Faq.Html page

### ISSUE THREAD

**Issue by slytechiefrommagentashore** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

there is no logo showing in Faq.html page and the upscroll button is not working and I would like to add some changes in Footer like adding links to the So, that when clicked on the Faq's it'll open Faq page or When clicked on signup It's redirected to the Signup page 

before 
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/97241435/9eef4d0b-cff9-4d31-81b9-cc205e82b88e)

I would Like to fix this issue 

### Expected behavior

the expected behavior, there should be a logo showing in faq page and when clicked on the links in footer page it should be directed to the concern pages and when clicked on the scrolled button it should be directed to the top page of faq's page 

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning

**Comment by slytechiefrommagentashore** [comment]
hello, I fixed the logo and the footer links, 
currently there is code for footer in every page of the website I would like to make changes such that there'll be a single code for footer in a separate file . i.e reusable footer
