### ISSUE TITLE
✨[Feature Request]: A mouse follower

### ISSUE THREAD

**Issue by Speedysays01** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As the website has black background, I can add a subtle mouse follower to make the site have more depth in UI

### Use Case

It will make all the other components look nicer and more highlighted because of the increased contrast between the black background, the mouse follower with neon but blurred tones and the actual elements. 

### Benefits

Will make the UI more interesting and site will be more responsive.

### Add ScreenShots

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/150716736/9ba577a6-6cf1-4e0a-863a-504ee6390119

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SheetalDawar** [comment]
i would like to work on this project, please assign this to me
