### ISSUE TITLE
🐞[Bug]: No Proper alignment of Patient section and Appointment section

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

No Proper alignment of Patient section and Appointment section

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/4627c080-598c-4d93-b27f-d1c1d2530b7e)

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/039e37c4-4d6d-4c17-8dba-cc289f408506)

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/e0a0c88a-3519-4ae4-82cf-dda6516d6418)

### Expected behavior

Alignment shoul be in center.
I want to rewrite the whole CSS and HTML code for both the sections.

### Add ScreenShots

Added in Bug section.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue under GSSOC

**Comment by Anjaliavv51** [comment]
@varshith257 if the changes are okay i will create a PR.

**Comment by varshith257** [comment]
Appointment form may change. Wait the new PR of appointment form merge

**Comment by Anjaliavv51** [comment]
@varshith257 i didn't get u

**Comment by varshith257** [comment]
There is an OPEN Pr of new Appointment form will merge it soon

**Comment by varshith257** [comment]
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/pull/299/

**Comment by varshith257** [comment]
But I think there many changes to appointment form

**Comment by Anjaliavv51** [comment]
> But I think there many changes to appointment form

@varshith257 okay

**Comment by varshith257** [comment]
Yes, I have closed. proceed with your changes

**Comment by Anjaliavv51** [comment]
@varshith257 review the PR.

**Comment by Anjaliavv51** [comment]
I had created one PR for both the issues #534 and #538

**Comment by varshith257** [comment]
OK
