### ISSUE TITLE
🐞[Bug]: Footer Section Alignment and UI Issues

### ISSUE THREAD

**Issue by DebapriyaJha** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

No Proper alignment of the footer section and the visual appearance and styling of the footer section is also not good.

Please assign this issue to me under gssoc 2024 and also add an appropriate level label to this issue.

### Expected behavior

The footer section should have a consistent and well-aligned layout. The positioning and spacing of elements should be visually appealing and follow best practices for user experience.

### Add ScreenShots

Now:
![fo1](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/111692420/8ffc6fde-0ecf-49f8-b72e-0a3e798c3958)
![fo2](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/111692420/a1bc8947-437a-401f-bdd3-12e36d8ccbc5)

My idea is somewhat like this:
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/111692420/14cfb1af-c8b6-4c1f-b523-5d548934676b)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning

**Comment by DebapriyaJha** [comment]
@Anishkagupta04 Please have a look at my PR and merge it. One more request as I have not only fixed the alignment issues but also added a new design to the newsletter and footer section thus enhancing the existing feature so if you can please increase the level 1 to level 2 it would help me a lot.
Thankyou
