### ISSUE TITLE
✨[Feature Request]: "Scroll to Top" Button and "Web Chat-Bot" Are Overlapping.

### ISSUE THREAD

**Issue by Tejashri-Taral** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I noticed that the "Scroll to Top" button and the Webchat bot are overlapping on the website.
This overlap affects the usability and accessibility of both features, making it difficult for users to effectively interact with the WebChat bot and the scroll top button.

### Use Case

Visibility Toggle: The button appears only when the user scrolls down a certain distance from the top of the page. This ensures that it doesn't obstruct the view unnecessarily but is readily available when needed.

Smooth Scrolling: Clicking on the button triggers a smooth scroll animation, ensuring a seamless transition back to the top of the page, rather than a sudden jump.

### Benefits

1) Improved User Experience
2) Enhanced Accessibility
3) Reduced Friction

### Add ScreenShots

**Before opening chatbot :**

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/160386036/e56e5af6-531a-4182-8bbe-c7448b1806ce)

**After opening chatbot :**

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/160386036/c1315004-05ca-474f-be90-c55ab12ef3ee)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Tejashri-Taral when the chatbot is used it will overlap the , Top arrow button .
I think their is no issue with that @varshith257

**Comment by Tejashri-Taral** [comment]
@Anishkagupta04 ,Please give me the level, After merging I didn't got any points..This was my first merged PR To get into the Leaderboard
