### ISSUE TITLE
✨[Feature Request]: Add "Website Visitor" Widget in Footer

### ISSUE THREAD

**Issue by rohitinu6** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a "Website Visitor" widget in the footer of the website that shows the number of visitors so far. This widget will update in real-time or upon page refresh to provide an accurate count of the total visitors.

### Use Case

This feature will enhance user engagement by providing visible visitor statistics and can be a useful metric for site administrators to track traffic.

### Benefits

- Provides a visible metric for tracking engagement.
- Enhances user experience by showing visitor statistics.
- Helps administrators monitor website traffic easily.

### Add ScreenShots

Preview of proposed Website Visitor Widget:

![Screenshot 2024-06-12 143634](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/113301503/35571e3b-08ed-42b9-8745-2cffb62c05b4)

**Please assign this issue to me under the gssoc label** 

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL
