### ISSUE TITLE
Add Icons to Navbar items

### ISSUE THREAD

**Issue by sailaja-adapa** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add Icons to Navbar items

Can you please assign me this issue under gssoc'24

### Use Case

It will make the website look  Attractive 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sailaja-adapa** [comment]
Please add label level 1 or level 2

**Comment by varshith257** [comment]
@sailaja-adapa It will be added later based on PR work. We have misconceptions with issue description and PR works earlier

**Comment by sailaja-adapa** [comment]
Okkkk
