### ISSUE TITLE
Add issues

### ISSUE THREAD

**Issue by Princegupta101** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#56]
As the maintainer of a Collaborate repo, keeping Issues up-to-date will help the student community understand what they can do to contribute. Issues should vary by the easy (update documentation) to the difficult (add a new feature). The more involved you are, the more opportunities there are to collaborate.

Recommendations:

Add issues of varying difficulty to the repo often. you must add the tag GSSoC'24, Level 1, Level2, Level 3 good first issue etc.
How we cacluclate the Scores on Leaderboard: Every PR one point
Level 1: 10 points
Level 2: 25 points
Level 3: 45 points
Try to add some documentation issues as well it would be easy for beginner contributor to explore opensource through your repo.
Generate issues even if you plan on solving them, so the repository appears as active.
Contribute/commit often to the repo so it does not go stale.
Reference https://github.com/Recode-Hive/Stackoverflow-Analysis/issues

**Comment by Gayathri-Pavuluri** [comment]
In this repo i want to add a section which stores the bills and prescriptions on the patient name which they can view online.
@varshith257   please assign this project foe me.

**Comment by Anishkagupta04** [comment]
Give a layout where you will add

**Comment by Gayathri-Pavuluri** [comment]
After they booked an appointment a profile is created to them ,under that patient profile, I'll add this section.
@Anishkagupta04  I'm Gssoc'24 contributor please assign this project for me.

**Comment by Anishkagupta04** [comment]
ANY UPDATES?

**Comment by Gayathri-Pavuluri** [comment]
Yeah i will post an update soon working on it
