### ISSUE TITLE
🐞[Bug]: Replace twitter icon with X

### ISSUE THREAD

**Issue by AkhilaSunesh** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/140897461/993e08c5-8b0d-49ec-84e8-46142a2445ad)
Location : footer

### Expected behavior

More professional outlook

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by IshaanXCoder** [comment]
Heyy @AkhilaSunesh , pls assign this issue to me!

**Comment by AkhilaSunesh** [comment]
> Heyy @AkhilaSunesh , pls assign this issue to me!

Hey, I am not the project admin. I am a contributor who has raised this issue. I think you have tagged the wrong person.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@Anishkagupta04
