### ISSUE TITLE
🐞[Bug]: Removing all the unwanted codes 

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

No bug
wanted to remove all the unwanted codes which is making the , file lenghty and also placing the css code in css file and html js in same way.Removing some unwanted file , which are not used atall.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue.

**Comment by Riyasharma1311** [comment]
please assign me this issue

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue.
