### ISSUE TITLE
🐞[Bug]: email is accepting in valid input

### ISSUE THREAD

**Issue by dnyandeepchute** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

email is accepting in valid input

### Expected behavior

email is accepting in valid input

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dnyandeepchute** [comment]
please assign this to me, thank you.

**Comment by Anishkagupta04** [comment]
assigning
