### ISSUE TITLE
🐞[Bug]: the submit text is not aligned

### ISSUE THREAD

**Issue by Shreyaa173** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the submit text is not aligned with the box

### Expected behavior

It would be in center

### Add ScreenShots

![Screenshot 2024-06-15 112511](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/144673309/a2a9904a-a788-44b3-90eb-cc46f83ecf01)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
