### ISSUE TITLE
✨want to add image at browser tab

### ISSUE THREAD

**Issue by Shreyaa173** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

want to add image at browser tab

### Use Case

it would be better that way

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/144673309/d5493551-1c47-4b0a-aff9-097f3138c107)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
already done
