### ISSUE TITLE
🐞[Bug]: Improve the UI of "about" section footer by fixing the "send message" option.

### ISSUE THREAD

**Issue by AnandK-pm** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The "Send Message" section has the text area for the message much smaller than its other components like Name , email.
I intend to fix this by improving the UI of this specific part.

### Expected behavior

The text area for the message box should be much larger for a user friendly experience. It will make the users frame their message much concisely.

### Add ScreenShots

![Screenshot 2024-06-15 121459](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142206618/f3b2e6e0-7165-45e2-8a6f-fd6971d9cf69)

### What browsers are you seeing the problem on?

Brave , Chrome
### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
already done
