### ISSUE TITLE
🐞[Bug]:  Missing Icons in some places

### ISSUE THREAD

**Issue by GAVINESHWAR** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The social media icons are missing in some pages , present in some places these will lead to bug , so I recommend to change that situation.

Asign me this isssue @Anishkagupta04 to contribute this project

### Expected behavior

Missing of social media icons lead to make user thought ,they are not have those accounts for the organization.

### Add ScreenShots

**Here all present**
Main Page
![Screenshot 2024-06-15 130607](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/124431955/704fe6ed-bbd9-4c62-99dd-cf2ff75cf020)
**Here some are missing**
Doctors listing page
![Screenshot 2024-06-15 130607](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/124431955/78306e5e-5b3a-4877-9963-985e31493d1e)
**In this page also**
Contact Page
![Screenshot 2024-06-15 130904](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/124431955/a940dc92-3454-4443-8f81-4a074ebcb7f0)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
