### ISSUE TITLE
🐞[Bug]: Fixing design of buttons

### ISSUE THREAD

**Issue by HarshitaJangde** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The design of Submit and Subscribe button should be adjusted. 

### Expected behavior

- The submit and subscribe button are too small and text too large for it to fit.
- submit text should also be centered.
- There's also an unnecessary gap after footer section.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146331595/f35eda28-ace4-4032-90ed-ac8fa93fa54b)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@Anishkagupta04
