### ISSUE TITLE
✨[Feature Request]: Responsive Navbar with Toggle Button

### ISSUE THREAD

**Issue by RohithChitrada** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The feature described is a Responsive Navigation Bar with a Toggle Button designed to adapt seamlessly across different screen sizes, particularly enhancing usability on mobile devices.

### Use Case

The responsive navigation bar is a user interface component that adjusts its layout and behavior based on the screen size of the device being used. It includes a toggle button that allows users to show or hide the navigation links when viewed on smaller screens, such as smartphones and tablets.

### Benefits

It will make the navbar responsive for the small screens.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by RohithChitrada** [comment]
I am a contributor participating in the GirlScript Summer of Code (GSSOC). I want to work on this feature. So, Please assign me.

**Comment by Riyasharma1311** [comment]
please assign me this issue

**Comment by RohithChitrada** [comment]
Bro this is a level 2 issue bro. I have submitted a PR but it is closed. I can still create another PR if you are willing to merge I will submit another PR

**Comment by varshith257** [comment]
@RohithChitrada Feel free to submit PR. You may not get immediate attention from me but within a week I will be back as my examination are ongoing
