### ISSUE TITLE
Dark/Light Mode Switcher

### ISSUE THREAD

**Issue by thevijayshankersharma** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#60]
Is your feature request related to a problem? Please describe.
Users often prefer different visual themes based on their preference or environmental conditions. However, many websites and applications lack the option to switch between dark and light modes, leading to discomfort for users in low-light settings or causing eye strain.

Describe the solution you'd like
Implement a dark/light mode switcher that allows users to toggle between different visual themes seamlessly. This feature should provide users with the flexibility to choose between dark and light modes based on their preference or environment.

Describe alternatives you've considered
One alternative is manually adjusting the brightness or contrast settings on the device, but this can be cumbersome and doesn't provide the same level of flexibility as a dedicated dark/light mode switcher.

Additional context
Integrating a dark/light mode switcher enhances user experience and accessibility, providing a more comfortable viewing experience for users in various lighting condition

**Comment by prachisah1** [comment]
I want to work on this feature please assingn  me this for gssoc 24 

I can also work on the 3rd feature which can add a different background to the page.

**Comment by Swapnil-Bhatnagar** [comment]
I want to work upon this , it would be great if you assign me this issue.
I will push the changes

**Comment by DARSHANITRIPATHI** [comment]
Please assign this issue to me.
