### ISSUE TITLE
✨Change Rate Us Page

### ISSUE THREAD

**Issue by sailaja-adapa** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to change rate us page like this in below image to make it more attractive 
I will change it according to our website

![emoji](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/161804629/ddddd73f-9859-449a-b24f-f8affc3ab53d)

can you assign me this issue under GSSOC'24 @varshith257 @Anishkagupta04 

### Use Case

It will Enhance Website Attractiveness

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@sailaja-adapa Also make it interactive by using the color scheme of our project

**Comment by sailaja-adapa** [comment]
yeah okk @varshith257 please assign label level 1 or level 2

**Comment by sailaja-adapa** [comment]
yeah okk @varshith257
