### ISSUE TITLE
🐞[Bug]: Alignment is not correct

### ISSUE THREAD

**Issue by theeayushkumar** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

submit button, username, password alignment is not correct

### Expected behavior

fix the problem

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/128235540/4c438387-d342-4e9d-9c60-f19c6df1c960)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Riyasharma1311** [comment]
please assign me this issue

**Comment by Anishkagupta04** [comment]
assigning
