### ISSUE TITLE
✨[Feature Request]: Enhancement of Feedback form

### ISSUE THREAD

**Issue by madhurima316** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to improve the emojis part , so that after selecting one emoji it remains prominent over others. I would also like to add the functionality that upon clicking submit button , it confirms that the form has been successfully submitted and thereafter the form should become blank again. I would also like to improve the look and hover effect of the Submit button .

### Use Case

It would become easier for user to understand if the form has been successfully submitted or not and if it has been filled out properly as they wanted it to be.

### Benefits

This enhancement would make the form and overall user experience better and smoother.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/145414858/e3c73568-0629-485d-b71f-f82f8307eae5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by madhurima316** [comment]
Please assign me this issue under GSSOC'24.

**Comment by Anishkagupta04** [comment]
assigning
