### ISSUE TITLE
🐞[Bug]: Redesign "Make an Appointment" Section on Homepage

### ISSUE THREAD

**Issue by AsmitaMishra24** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The "Make an Appointment" section on the homepage currently faces issues with color consistency and non-functional buttons, impacting user interaction and experience negatively. Key objectives are:

**Color Consistency:**
- Ensure uniform color usage throughout the section to maintain visual harmony and brand identity.

**Button Functionality:**
- Investigate and fix non-functional buttons to enable users to schedule appointments seamlessly.

### Expected behavior

**Visual Consistency:**
1. Colors aligned with brand identity, enhancing readability.
2. Clear and visually appealing design for buttons and form elements.

**Button Functionality:**
1. Responsive buttons that trigger appointment scheduling.
2. Immediate and clear feedback upon button interaction.

**Accessibility and Usability:**
1. Compliance with accessibility standards (e.g., WCAG).
2. Intuitive user experience with clear instructions and navigation.

**Integration and Reliability:**
1. Seamless integration with scheduling systems.
2. Consistent performance across browsers and devices.

**Feedback Mechanism:**
1. Option for users to provide feedback or contact support.

**Testing and Validation:**
1. Regular testing to ensure functionality and usability standards are met.

### Add ScreenShots

![Screenshot 2024-06-17 014522](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146121869/cc22e83f-2275-47cb-a19b-ee0ee87be255)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
