### ISSUE TITLE
🐞[Bug]:  Text not Visible While hovering 

### ISSUE THREAD

**Issue by GAVINESHWAR** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In this website there are some bugs include not invisible of text while hovering, missing placeholder in appointment form , and more.

### Expected behavior

In this lead to improper view of context user will unable to view while hovering , not understand what to fill in the input field and more

### Add ScreenShots

These are the some bugs photo
text not visible while hovering:

![Screenshot 2024-06-17 093121](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/124431955/de5157b6-1012-4ba4-86d4-98fffcef7f1e)

button text not done proper padding

![Screenshot 2024-06-17 093224](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/124431955/288a9391-24f6-4fd5-9726-f85aa5d9b746)

Text not view clearly to entire divs:

![Screenshot 2024-06-17 093552](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/124431955/d869be56-9ee3-49bc-8269-3183ee3f1d7e)

Assign me this issue @Anishkagupta04  sir to make contribution to this project

Thank you

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
