### ISSUE TITLE
🐞[Bug]: Navbar is not responsive

### ISSUE THREAD

**Issue by meetarora10** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The navbar is not properly aligned for the responsive view.

### Expected behavior

Assign this task to me and I can create a responsive navbar added with other styling.

### Add ScreenShots

![Screenshot (474)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/143121854/74cbcf0a-eb1b-4d0c-8b1e-8e223c553910)

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
