### ISSUE TITLE
Adding Cursor Animation✨[Feature Request]: 

### ISSUE THREAD

**Issue by SagarRathore1** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#614]
### Feature Description

I would like to add cursor animation .

### Use Case

I would like to add cursor animation to make website more attractive and professional .

### Benefits

It will enhance user experience .

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/169483518/13d5df51-b28f-429d-9aee-6e74b40587fb)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/169483518/327c9430-efb4-4de5-9cb5-eba6f19cb380

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and I would love to contribute, can you please assign me this issue.

**Comment by Satyndr** [comment]
Hello @Anishkagupta04 , I would like to contribute to this project , can you please assign mw this problem.

**Comment by varshith257** [comment]
Hey @Soujanya2004 @Satyndr 👋 

Thanks for your interest to contribute to this project. There are many open old  issues which are open. Tag me there if you incase want to work on them :)

**Comment by Satyndr** [comment]
@varshith257 yes, I want to work
