### ISSUE TITLE
✨[Feature Request]: Login page is not appearing good

### ISSUE THREAD

**Issue by ayushrskiaa** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The login page absolutely needs improvement.

### Use Case

It makes the web page more attractive to the users.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/130389607/30f3af65-828b-4a1e-af8f-62f9e9f7670e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ayushrskiaa** [comment]
please assign it to me 
Thank you

**Comment by Anishkagupta04** [comment]
provide layout how you are thinking it should be

**Comment by Simmi019** [comment]
i would like to work on this !please assign it  to me.

**Comment by ayushrskiaa** [comment]
@Anishkagupta04 
This is my design
![Patient Portal](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/130389607/df32d395-2cd4-4039-9b97-1502d7bcffb6)
