### ISSUE TITLE
🐞[Bug]: The elements on the screen are not aligned to the center.

### ISSUE THREAD

**Issue by ayushrskiaa** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The elements on the screen are not aligned to the center.

### Expected behavior

Ensure that the elements are positioned in the center.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/130389607/7457b030-492d-435b-aa9c-a92cb71ebe02)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ayushrskiaa** [comment]
Assign me this issue I want to work on it.
Thank you

**Comment by Anishkagupta04** [comment]
assigning
