### ISSUE TITLE
[Feature] Button to toggle between Dark mode and  Light mode

### ISSUE THREAD

**Issue by tat-tvam-asii** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#62]
I would like to add a button to toggle between dark mode and light mode.

**Comment by RekhaKushwaha01** [comment]
I would like to work on this please assign it to me

**Comment by prachisah1** [comment]
Hello @tat-tvam-asii 
I want to work on this feature please assing me this  
![Uploading b1cd961e-d514-4fa9-acf8-230be28f90ac-cover.png…]()
