### ISSUE TITLE
Each doctor review can be provided to build the trust

### ISSUE THREAD

**Issue by KavyaBS123** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the doctors section of the website where each doctors experience and qualification is been provided additional review of each them can be given which can build trust for the upcoming patients

### Use Case

It improves UI as well as build trust for website user

### Benefits

It improves UI as well as build trust for website user

### Add ScreenShots

![Screenshot (446)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/148982177/fe95b2fe-d6b5-47cd-a86d-863129725389)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
