### ISSUE TITLE
✨[Feature Request]: Enhancement of UI:  and responsiveness of navbar | contact form input boxes alignment and size fix | footer form alignment | Patient portal input boxes improvement

### ISSUE THREAD

**Issue by Garimas10u** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The following enhancement needs to be done:
1. Adding Navbar Dropdown
2. Responsiveness of navbar
3. Fixing Contact form input boxes alignment and size  
4. Fixing footer form alignment
5. UI of Patient portal input boxes 

### Use Case

It will enhance the user experience
the navbar is too congested
Adding a dropdown will make the website neat
Proper input boxes will enable the user to fill in the information properly

### Benefits

It will improve the front end of the project and will enable the users to have a better experience visiting the website.
The website will have a modern UI which will enhance the user experience

Good contact form will invite kore feedbacks and visitors to the website

### Add ScreenShots

![Screenshot 2024-06-17 232353](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/130840612/8e59070c-049d-4749-8265-bf1acf9e0497)
![Screenshot 2024-06-17 232410](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/130840612/a26ba4ad-8494-4c1e-a3cb-ef818c5ba9e5)
![Screenshot 2024-06-17 232445](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/130840612/2f8cbec7-ff1b-4f4a-8648-088adbd524ff)
![Screenshot 2024-06-17 232508](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/130840612/bd416d42-e36c-4b13-914b-a2e2744439c3)
![Screenshot 2024-06-17 232527](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/130840612/2dcc57d9-d018-4d36-934b-ad27b9891247)
![Screenshot 2024-06-17 232609](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/130840612/d5860215-aeee-4b14-ae09-a517a00619a3)
![Screenshot 2024-06-17 232619](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/130840612/701d890b-196c-4178-9861-d3a5470f1091)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Garimas10u** [comment]
Please assign me the issue as I would like to work on it

**Comment by Anishkagupta04** [comment]
assigning

**Comment by Garimas10u** [comment]
Thank you for assigning the issue

**Comment by gaaurav03** [comment]
hey, just wanted to know if the issue is still open as i wanted to contribute .
