### ISSUE TITLE
🐞[Bug]: Footer of the faq.html page is different from the home page footer

### ISSUE THREAD

**Issue by slytechiefrommagentashore** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The footer of the Faq.html page is different when compared to the footer of the Home page. 

### Expected behavior

footer should be same in the faq and home page 

### Add ScreenShots

before 
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/97241435/d5c0f52b-8dc1-414e-bbb0-090272fe61a5)
 after 
 
 
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/97241435/4e20279f-cdcf-47b2-bbfc-3ae424fe833d)

I would like to make changes to the footer of the faq.html page 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
change the footer which is currently
