### ISSUE TITLE
✨[Feature Request]: Add Elegant and Asthetic Animated BUttons in News Page Section

### ISSUE THREAD

**Issue by AbheetHacker4278** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I have changed the background of the news page which is completely made up of CSS and also changed the button to Animated buttons.

### Issue:
#634 

### Benefits

user experience is improved from previous also animations which i have used , is not lagging in any device and also it is responsive in nature.

### Before:
![Screenshot 2024-06-18 024008](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/114290748/95827935-f9ad-4344-b4d1-f434e7241eb3)

### After:
![Screenshot 2024-06-18 162414](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/114290748/9a8410e9-15f8-4676-a328-2ad8693d2453)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Simmi019** [comment]
i would like to work on this!! plz assign it to me under gsooc label

**Comment by AbheetHacker4278** [comment]
> i would like to work on this!! plz assign it to me under gsooc label

I already issue the PR
