### ISSUE TITLE
✨[Feature Request]: Slight Grammatical error in the chatbot part.

### ISSUE THREAD

**Issue by karishmaaa101** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is a slight grammatical error in the chatbot section.
The bot should greet the user and say : 
**Hi there. I hope you are keeping yourself hydrated throughout.**
**"How can I help you today?"**

### Use Case

_The project will be enhanced as there will be better communication between the chatbot and the user._

### Benefits

Better greetings will help the user to communicate clearly and share their problems.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/104766763/10649947-a3f5-4fd0-b75c-77030300eb92)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Simmi019** [comment]
i would like to work on this  ! plz assign it to me under gsooc labels.
