### ISSUE TITLE
Add Contribution Instructions for GitHub Repository

### ISSUE THREAD

**Issue by PradnyaGaitonde** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#65]
I would like to request adding contribution instructions to the README.md file of the repository. These instructions will provide a quick start guide for users to contribute to the project. They include steps such as starring and forking the repository, cloning the forked repository, creating a new branch, installing dependencies, and opening a pull request. I believe these instructions will help streamline the contribution process and encourage more users to contribute to the project. 
Could you please assign me this task under gssoc24?

**Comment by Anishkagupta04** [comment]
assigning

**Comment by PradnyaGaitonde** [comment]
I wanted to kindly request adding the "gssoc24" label to the issue to indicate its association with the program. Additionally, it would be helpful to include a level number label (e.g., "Level-1", "Level-2", etc.) to denote the difficulty level of the issue.
