### ISSUE TITLE
No proper README.md Structure

### ISSUE THREAD

**Issue by r7projects-shayan** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#66]
# Issue Description

The README.md file is not properly structured and it's missing the tech stack, screenshots and important links to code of conduct and contributing.md files. 

# Steps to reproduce 

Update the README.md file to a proper structure, add the tech stack, screenshots and important links 

# Labels 

Gssoc 24

# Priority 

High

**Comment by r7projects-shayan** [comment]
@Anishkagupta04 I have prepared a proper README.md file for Rapiddoc Healthcare Website,  it would be great if you assign me this issue. 

I will push the changes right away.

**Comment by Swapnil-Bhatnagar** [comment]
@Anishkagupta04 I want to work upon this, it would be great if you assign me this issue.

**Comment by r7projects-shayan** [comment]
@Anishkagupta04 please add the labels for gssoc and issue level so that the project gets verified
