### ISSUE TITLE
✨[Feature Request]: Addition of navbar and footer and improvement in the ui of  signin and signup page that match the theme

### ISSUE THREAD

**Issue by DiwareNamrata23** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

<img width="1440" alt="Screenshot 2024-06-21 at 11 09 18 AM" src="https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142529986/bfb15437-374f-4253-a4f2-3dd175840bcb">
Using html and css the styling should be changed to the required design.

### Use Case

 Addition of navbar and footer and improvement in the ui of  signin and signup page that match the theme.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by DiwareNamrata23** [comment]
@varshith257 can you please assign this issue to me

**Comment by shashbh18** [comment]
I would love to work on it.Please assign this issue to me.

**Comment by DiwareNamrata23** [comment]
I will add new pr
