### ISSUE TITLE
Replace old twitter icon with new icon

### ISSUE THREAD

**Issue by antriksh-9** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#67]
On the [webiste](https://69glitch.github.io/RapiDoc/#) under contact section the twitter logo is still the old one.
It needs to be updated.

**Comment by antriksh-9** [comment]
Hey @Anishkagupta04 , I want to work on this issue.
Please assign me under GSSoC '24.

**Comment by Swapnil-Bhatnagar** [comment]
Hi @Anishkagupta04 . I want to work upon this , it would be great if you assign me this issue please..
I will push the changes

**Comment by DARSHANITRIPATHI** [comment]
Please assign this issue to me.

**Comment by Anishkagupta04** [comment]
@antriksh-9 assigning

**Comment by Priyanshuthapliyal2005** [comment]
i can work on this

**Comment by Priyanshuthapliyal2005** [comment]
<glyph unicode="&#xeecc;" glyph-name="bxl-twitter" d="M837.675 618.795c0.555-7.467 0.555-14.891 0.555-22.315 0-227.2-172.928-489.003-488.96-489.003-97.365 0-187.819 28.203-263.936 77.184 13.824-1.579 27.136-2.133 41.515-2.133 80.341 0 154.283 27.136 213.376 73.429-75.563 1.579-138.88 51.072-160.725 119.168 10.624-1.579 21.291-2.645 32.469-2.645 15.403 0 30.891 2.133 45.269 5.845-78.805 15.957-137.813 85.12-137.813 168.661v2.133c22.912-12.757 49.493-20.736 77.653-21.803-46.293 30.805-76.629 83.499-76.629 143.104 0 31.915 8.491 61.184 23.381 86.699 84.608-104.235 211.797-172.373 354.389-179.84-2.645 12.8-4.267 26.069-4.267 39.381 0 94.72 76.629 171.861 171.861 171.861 49.493 0 94.165-20.736 125.568-54.272 38.827 7.467 76.032 21.845 109.056 41.515-12.757-39.893-39.936-73.429-75.563-94.72 34.603 3.755 68.139 13.312 98.944 26.624-23.381-34.048-52.608-64.384-86.144-88.875z" />


this is which type  of twitter logo i dont understand how can i change this logo with new logo
