### ISSUE TITLE
Contact form redesign

### ISSUE THREAD

**Issue by 21pa1a6149** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In contact section for send message section is not looking good and not alligned correctly

### Expected behavior

I will make the send message section in contact to be alligned and designed correctly to look good

### Add ScreenShots

![Screenshot 2024-06-22 153436](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/126564098/a575b132-024c-4633-a7a7-ce517c7e0a76)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by minakshikr7** [comment]
I would like to work on this issue. Please assign this task to me under @GSSoC24
