### ISSUE TITLE
✨[Feature Request]: Make site responsive for all devices

### ISSUE THREAD

**Issue by shubham72-73** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, the website is looking good in desktop devices only. Site would be responsive for all the devices after CSS would be implemented correctly. Please assign me this issue under GSSOC'24.

### Use Case

Better User Experience on all screen sizes. Below image show how the website looks on a smartphone.

### Benefits

Website will be fully responsive. Will work and look great in Desktop, Tablet and Mobile devices.

### Add ScreenShots

![Screenshot 2024-06-24 201844](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/133738315/7810c0b2-21d4-4fdf-aafe-d152fe621b91)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
