### ISSUE TITLE
Secure Patient Portal Development

### ISSUE THREAD

**Issue by shreyaslal** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#69]
I aim to create a secure patient portal where users can access their medical records, lab results, and prescription history. It shall also allow patients to communicate securely with healthcare providers, request prescription refills, and view upcoming appointments.
Could you please assign me this issue? I am eager to get started and contribute to the project's progress.
Shreyas

**Comment by Anishkagupta04** [comment]
@shreyaslal assigning

**Comment by shreyaslal** [comment]
Thank you for merging the PR! Could you kindly label this issue under GSSoC'24 and mention the appropriate level that you think is suitable for resolving this issue?
Regards
Shreyas | GSSoC'24

**Comment by varshith257** [comment]
@shreyaslal Added
