### ISSUE TITLE
🐞[Bug]: 

### ISSUE THREAD

**Issue by adityapandey78** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

>selecting time slot div is not properly aligned
>make an appointment section is not good as per the UI 
>Padding not good for the make an appointment
>Updating the favicon of rapidoc with logo of Rapidoc
>Select time not working properly
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/140270777/6e9a2c06-23d0-4606-8c6b-1fbdaeccb9f1)
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/140270777/c2fe6a46-9848-4602-b7c3-e16de1b7e91d)
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/140270777/b0159ce9-b8b2-4cc3-ae4c-d55a5bdfe388)

### Expected behavior

![WhatsApp Image 2024-06-25 at 07 41 42_19c783d0](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/140270777/fdb8a394-fc22-4c2c-ab5b-a9f8369139d0)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by adityapandey78** [comment]
@Anishkagupta04  Please assign this issue to me under GSSOC with the required levels.
Thanks

**Comment by kashi-verma** [comment]
I can perfectly allign these assets  so @Anishkagupta04  pls assign me this issue  since it is vey important for me.
Thank you and waiting for your response.

**Comment by Anishkagupta04** [comment]
could you do like to make a serate page for this instead on the main page as its seems to look messy

**Comment by adityapandey78** [comment]
Yes sure @Anishkagupta04  please assigne this issue to me under gssoc with required label, thanks
