### ISSUE TITLE
🐞[Bug]:  Social Media in Footer Section 

### ISSUE THREAD

**Issue by puneet426** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

social media icons in footer section is too small it needs some improvements
![Screenshot 2024-06-25 083619](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/168094736/cdb63b17-63b9-43f7-bce1-396206b38848)

### Expected behavior

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/168094736/37538be3-fa58-4cfe-a348-a53995126e64

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by puneet426** [comment]
@varshith257  please assign this issue to me

**Comment by puneet426** [comment]
@Anishkagupta04 please assign this issue to me

**Comment by Anishkagupta04** [comment]
assigning
