### ISSUE TITLE
🐞[Bug]: Sign in and Sign up Button in Header Section

### ISSUE THREAD

**Issue by puneet426** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the sign in and sign up button is same so we can make different buttons for that
![Screenshot 2024-06-25 084929](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/168094736/92c75dd4-730e-4f8a-a045-3a0399e20155)

### Expected behavior

MAde different buttons for it

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by puneet426** [comment]
@varshith257 please assign this issue to me under GSSOC

**Comment by puneet426** [comment]
@Anishkagupta04 please assign this issue to me

**Comment by Anishkagupta04** [comment]
where will you add that button then?

**Comment by puneet426** [comment]
when i hover on sign in button it also show on sign up button so i wanted to make two buttons like find a doctor

**Comment by puneet426** [comment]
![Screenshot 2024-06-27 151910](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/168094736/222f7a94-3ff0-43ec-9a70-79ed409813c3)

**Comment by puneet426** [comment]
find a doctor button needs some margin because it is attached to scrollbar
