### ISSUE TITLE
✨[Feature Request]: Dark And Light Theme

### ISSUE THREAD

**Issue by puneet426** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

on the home page we can add Dark and light background button to change the theme 

### Use Case

to change the theme of page according to person as someone is used to light theme and other dark theme

### Add ScreenShots

![Screenshot 2024-06-25 090539](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/168094736/0342d0cb-e8a6-49a4-a6e5-c8558ea027b3)

i want to add button like that in the navbar
![Screenshot 2024-06-25 090618](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/168094736/e564efb2-02e9-412b-bc70-12d4cd8269f4)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by puneet426** [comment]
@varshith257 or @Anishkagupta04  please assign this issue to me

**Comment by kou95shik** [comment]
@varshith257 or @Anishkagupta04 Please assign me this issue, i will work on it.
