### ISSUE TITLE
🐞[Bug]: Add functionality to feedback form

### ISSUE THREAD

**Issue by ananyag309** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The feedback form is currently not accepting response. I want to add functionality to it, please assign this issue to me under gssoc @ans

### Expected behavior

It will accept the response and display a confirmation message

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
