### ISSUE TITLE
✨[Feature Request]: better hover effect on footer elements

### ISSUE THREAD

**Issue by heli0707** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To create a better hover effect in the footer, use CSS to smoothly transition the background color, text color, and add an underline when users hover over the links.

### Use Case

Improve the user experience by providing clear visual feedback when users interact with footer links.

### Add ScreenShots

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/95361125/262923aa-9182-4000-8c60-c44e20a913fb

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning

**Comment by heli0707** [comment]
When i received points !?

**Comment by heli0707** [comment]
The issue has been closed, but I have not received any points. Why? Sent from Mail for Windows From: Anishka GuptaSent: 03 July 2024 20:58To: Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-Cc: Heli Detroja; AssignSubject: Re: [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-] ✨[Feature Request]: better hover effect on footer elements (Issue #699) Closed #699 as completed via #722.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
