### ISSUE TITLE
addtion of functionalities at services section

### ISSUE THREAD

**Issue by kumar1397** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#7]
We can integrate this project with Google Maps API.
Upon interaction with clinics and blood bank cards, Google Maps API will provide some fake locations of hospitals and blood banks near the area produced by a user.
So, please assign me this issue to work under GSSoC '24.
![Screenshot 2024-05-09 210919](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/122858524/646022cc-2e91-4969-84bc-7d4cacf28407)

**Comment by Sathya-reddy1658** [comment]
I've been working on API's recently I think I can solve this issue better

**Comment by Anishkagupta04** [comment]
So are you fine with working together all three of you?

**Comment by kumar1397** [comment]
Madam,
I have worked on such kinds of projects.  I have a personal interest in working on this particular issue alone to gain a deeper understanding and improve my skills. 
So I want this issue to be assigned to me.

**Comment by Sathya-reddy1658** [comment]
> So are you fine with working together all three of you?

yes!!!

**Comment by Anishkagupta04** [comment]
Then proceed 🫶

**Comment by varshith257** [comment]
@Sathya-reddy1658 It's the contribution to work on separately. @kumar1397 is also willing to solve the issue himself. If Kumar doesn't make any progress will assign it as collaborative issue

**Comment by varshith257** [comment]
@Sathya-reddy1658 @nidhaahmed Thanks for your enthusiasm for solving this issue. Meanwhile you can look at another issues to contribute for this project :)

**Comment by varshith257** [comment]
@kumar1397 What's the updates on this work?

**Comment by kumar1397** [comment]
> @kumar1397 What's the updates on this work?

I will push the code soon. I just need some time. 
Thank you

**Comment by Anishkagupta04** [comment]
ANY UPDATES?

**Comment by kumar1397** [comment]
> ANY UPDATES?

please check the PR #255
