### ISSUE TITLE
🐞[Bug]: without account creation login is sucessfull

### ISSUE THREAD

**Issue by Subhams-GIT** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Login is still sucessfull even if account is not created.

### Expected behavior

login should be after sign up only 

### Add ScreenShots

![Screenshot 2024-06-25 124537](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/143584912/259ed8f0-bc05-4408-8aa3-b6b330a7ae9a)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
