### ISSUE TITLE
🐞[Bug]: Three social media icons are not redirecting into their pages.

### ISSUE THREAD

**Issue by theashikagupta** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Three social media icons(Instagram, Phone no ,Gmail) are not redirecting into their pages.

### Expected behavior

Like facebook ,Twitter it will redirect into their respective pages

### Add ScreenShots

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/136061047/d6393783-2f81-4670-a3ff-7e80b8fe88a3

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by theashikagupta** [comment]
@Anishkagupta04 Kindly assign me this issue under GSSOC'24

**Comment by Anishkagupta04** [comment]
assigning

**Comment by theashikagupta** [comment]
@Anishkagupta04 Mam I sent you a mail kindly check it and give reply
