### ISSUE TITLE
Database Support for forms and various registrations

### ISSUE THREAD

**Issue by varshith257** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#705]
### Discussed in https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/discussions/455

<div type='discussions-op-text'>

<sup>Originally posted by **varshith257** June  6, 2024</sup>
PostgreSQL is one I prefer as I worked with three of these dbs. But I can't say we use this only for our project as every usecase has other preferences over dbs in projects. Submit a report of your findings, why we prefer PostgreSQL for our project, and why not MongoDB and MySQL. Pros and cons of them and what you are suggesting to use finally based on your research?</div>

**Comment by varshith257** [comment]
@Pruthaa17 Can you make a PR with the DB schema image in an assets folder in root?

**Comment by Pruthaa17** [comment]
@varshith257 Sure I can , before that please can you review this ?? https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/discussions/455#discussioncomment-9712931
