### ISSUE TITLE
🐞[Bug]: Contact Form Placeholder Text

### ISSUE THREAD

**Issue by Changingthegame** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the contact section on the main page of the website, there are input fields for "Name", "Email", "subject" and "Message". Each of these fields has placeholder text (e.g., "Your Name"). However, there are two problems with the current functionality :

Placeholder Text Visibility: When a user clicks or tabs into the field, the placeholder text does not disappear. This makes it difficult for users to see what they are typing.
Text Visibility While Typing: While typing in the input fields, the entered text is not visible until the cursor is moved away from the field. This makes it challenging for users to know if they have entered the correct information

### Expected behavior

The placeholder text should disappear when the input field is focused and the entered text should be visible while typing in the input field making it suitable for the user to see what they are typing.

### Add ScreenShots

![Rapidoc_1](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/169473705/a831a561-6b6a-4408-9d3b-3b66788fa395)

![Rapidoc_2](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/169473705/f9af6ad4-6a96-453d-b495-573b3a42e77f)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by minakshikr7** [comment]
I would like to work on this issue. Please assign this task to me under @GSSoC24
