### ISSUE TITLE
🐞[Bug]: SignUp successful without email verification | Login Successful with Incorrect Passwords | 'Forgot Password' doesn't work | 'Remember Me' doesn't Work| SignUp/Login from Google doesn't work

### ISSUE THREAD

**Issue by Nidhi-Satyapriya** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Issues:
1) **Sign-Up Successful Without Email Verification:** Users can register with any random mail ids, even with a non-existent mail id too.
2) **Login Successful with Incorrect Passwords:** Users can log in even with incorrect passwords.
3) **'Forgot Password' Functionality Not Working:** The password reset process  is not functional.
4) '**Remember Me' Feature Not Functional:** The option to keep user's id and password in memory is not functional
5) **Google/Facebook Sign-Up/Login Integration Fails:** 

### Expected behavior

1) A valid Sign-Up with email verification using OAuth or JWT.
2) Login only if the credentials match.
3) An eye button while signing up,  'reconfirm password'  entry and 'Remember Me' feature for convenience.
4) Sign-Up/Login with Google.

### Add ScreenShots

![Screenshot 2024-06-29 103102](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/123321320/c1973424-4c0a-4963-a3b1-df76be9886aa)
![Screenshot 2024-06-29 103019](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/123321320/73f0b52f-a21a-49df-a0f6-8144b085d26d)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Nidhi-Satyapriya** [comment]
@Anishkagupta04  kindly assign this to me with a tag.

**Comment by Nidhi-Satyapriya** [comment]
what are your views on this? @varshith257 @Pruthaa17 @Anishkagupta04

**Comment by varshith257** [comment]
I think it is better when we support db to our project along with the backend.

@Pruthaa17 had designed the schema tables

**Comment by Nidhi-Satyapriya** [comment]
Okay @varshith257 sir. Do let me know when required. May I know why it's been assigned these tags though?

**Comment by varshith257** [comment]
We aren't yet for this. If we have a valid decision from Admin we can proceed
