### ISSUE TITLE
🐞[Bug]: Unneccesary redirecting to a seperate 'Rate us' and 'Contact Us' page when it should be routed to the 'Rate Us' section and the 'Contact Us' section  respectively present at the bottom of the home page 

### ISSUE THREAD

**Issue by Nidhi-Satyapriya** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On clicking the 'Rate Us' tab or the 'Contact Us' tab, it redirects to  seperate pages. This is unnecessary. Like the 'about', 'service', 'patient portal' , this too should redirect to the 'Rate Us' section and the 'Contact Us' section  respectively present at the bottom of the home page .
This ensures the **consistency of the website, without cluttering it with unnecessary redirects.** 
**Routing of the navbar should be handled correctly too for a consistent user experience.**

### Expected behavior

1) On clicking the 'Rate Us' tab, redirect to the 'Rate Us' section of the home page .
2) On clicking the 'Contact Us' tab, redirect to the 'Contact Us' section of the home page .

### Add ScreenShots

Direct to this:-
![Screenshot 2024-06-29 105558](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/123321320/9d94dc03-a608-4ff0-83e8-0c61a834e701)
instead of creating a whole new page:-
![Screenshot 2024-06-29 105614](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/123321320/f5503b82-02a7-49f2-86b6-b93f0dea5279)
for contact us, direct to this, instead of creating a whole new page:-[design can be improved]
![Screenshot 2024-06-29 112438](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/123321320/207294f1-8b3a-4156-a1e8-c508e663f564)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Nidhi-Satyapriya** [comment]
@Anishkagupta04 kindly review this.

**Comment by Nidhi-Satyapriya** [comment]
@Anishkagupta04 @varshith257 @Pruthaa17  Hi! did you have a look on this?

**Comment by Nidhi-Satyapriya** [comment]
@varshith257 @Anishkagupta04 @Pruthaa17  Hey!bI made a PR. Kindly review it at your convenience.

**Comment by varshith257** [comment]
@Nidhi-Satyapriya Will review it bu EOD
