### ISSUE TITLE
✨[Feature Request]:  Add a Back-To Home Button on the Login Page

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Anishkagupta04  and @varshith257 

I noticed that the login page currently does not have any means to navigate back to the home page. This can be inconvenient for users who might want to return to the home page without logging in.

I would like to suggest adding a "Back to Home" button on the login page for easy and quick navigation. This will improve the user experience by providing a straightforward way to return to the home page.

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/163530398/9ca530cb-5c54-45a3-9e73-de24c9b711c4)

I am interested in implementing this feature and would like to request to be assigned this issue under GSSOC'24.

### Use Case

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by IshaanXCoder** [comment]
@Anishkagupta04 pls assign me with this issue, you'll definitely like my work!

**Comment by RadhikaMalpani1702** [comment]
@Anishkagupta04 and @varshith257 

Please assign this issue to me.
