### ISSUE TITLE
✨[Feature Request]: Fix Navbar Design and Redesign

### ISSUE THREAD

**Issue by MinavKaria** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to update the navbar to improve the design and functionality. Currently, there are a lot of icons in the navbar and the container does not have a max width set, causing it to appear cluttered and unorganized. I would like to implement a fixed max width for the container to ensure a clean and consistent layout.

### Use Case

A good-looking navbar can significantly enhance the user experience on a website or application by providing easy navigation and access to important features. Here are some use cases and advantages of a well-designed navbar:

### Benefits

1. Easy navigation: A clean and organized navbar makes it easy for users to find their way around a website or application. This can be especially useful for complex or content-heavy sites where users may struggle to find what they are looking for.

2. Improved user engagement: An attractive navbar can encourage users to explore different sections of a site, leading to increased engagement and interaction with the content. This can ultimately result in longer time spent on the site and higher conversion rates.

3. Mobile responsiveness: A responsive navbar that adapts to different screen sizes and devices ensures a seamless user experience across all platforms. This is particularly important as more and more users are accessing websites and applications on mobile devices.

4. Access to key features: A well-organized navbar can highlight important features, pages, or calls-to-action, making it easier for users to access the most relevant information. This can help drive conversions and achieve business goals.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/119132631/6edd7d24-1ebd-49bd-a9cc-76b42b964265)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Satyndr** [comment]
I want to work on this issue, please assign me this issue and also add label for it.

**Comment by Satyndr** [comment]
hey @varshith257 I want to work on this issue, please assign me this issue and also add label for it.

**Comment by MinavKaria** [comment]
I also want to work on this @varshith257 Please assign it to me

**Comment by MinavKaria** [comment]
@varshith257 Please acknowledge

**Comment by varshith257** [comment]
Hey @MinavKaria 👋! Here you go ....

**Comment by varshith257** [comment]
@MinavKaria If you don't get replies from me just tag by next day. I usually get lot of messages of GitHub so I can't verify which have been tagged to me :)

**Comment by varshith257** [comment]
@MinavKaria If you don't get replies from me just tag by next day. I usually get lot of messages of GitHub so I can't verify which have been tagged to me :)
