### ISSUE TITLE
✨[Feature Request]: Add functionality to Daily Newsletter

### ISSUE THREAD

**Issue by ananyag309** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When we click on subscribe button error page open.
![p](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/145869907/bb6847a5-e0fc-4a51-b199-a49ec5755b79)

### Use Case

I want to add functionality to daily newsletter so it accept response and display confirmation.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anishkagupta04** [comment]
assigning
