### ISSUE TITLE
🐞[Bug]: Unify Footer and Navbar in the Blood Test Page

### ISSUE THREAD

**Issue by Anjaliavv51** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Add the current navbar and footer of the home page to the blood test page

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/117595548/d28261db-72f1-418d-b2d2-5a534591bbc2)

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/117595548/3ba0ee7e-07e8-4960-ae31-b38222d44492)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this issue

**Comment by varshith257** [comment]
@Anjaliavv51 See issue description
