### ISSUE TITLE
Redesign the footer section

### ISSUE THREAD

**Issue by PrachiJadhav2310** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The footer alignment does not seem to be correct and attractive.

### Suggested Change

Footer should look neat properly organised and sober.Please assign me this so that i can redesign this page.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@PrachiJadhav2310 What do you think to be changed?
Can be detailed the issue description?
