### ISSUE TITLE
➕Enhancement: Improving "UI and Functionality" Of the Feedback Form

### ISSUE THREAD

**Issue by aslams2020** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Anishkagupta04 and @varshith257,

Here is the the Enhancement I Propose to do - 
Currently, the feedback form on the website **requires improvements to enhance user experience and functionality.** 
I **want to make several enhancements** to the form to align it **better with the website theme** and improve usability.

Here is the current Feedback page - 

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131389695/0262c179-b6a9-4a8d-9fa2-51c1a00c6356)

### Here's What Will I Do - 

1. **UI Enhancement:** **Update the UI to match the website theme** for consistency and better user experience. 
2. **Rating System:** Modifying the **Rating system** to make it more intuitive and user-friendly.
3. **"Custom Success Popup":** Implement **a custom popup to notify users** upon successful form submission.
4. **Real Email Sending Integration:** Integrate real email sending functionality using Formspree.io to notify the admin of new feedback submissions. (This is a great functionality to add )
5. Styling the Current "Submit" Button with much better Hover Effects! 
6. Additionally, **I will try to add animations** wherever Needed.

I hope I was able to explain you the solution.
Please assign me this issue under GSSoC'24.

### Use Case

If the feedback form itself has a creative UI and engaging functionalities, The user will tend to give feedbacks about the website often times.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by aslams2020** [comment]
Hey @varshith257, Thankyou for assigning.
Should I Implement Real Email Sending Functionality using Formspree.io? (4th point mentioned in issue)
It's a efficient functionality!
(before merging the PR if Demo looks good to you, i'll just need your ID of Formspree to give you full access to receiving emails.) 
Please confirm this one. I will do the Rest for sure. 

This was my previous work using formspree.
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/131389695/5ecaa0e6-26f2-47a6-ad9b-efa693a8d329)

Thankyou!

**Comment by varshith257** [comment]
@aslams2020 Good idea! Maybe rather we receive emails for each rating better if we store ratings in the db and query as required

**Comment by aslams2020** [comment]
@varshith257, I understand your preference for storing ratings in the database and querying them . However, Implementing using Formspree.io is straightforward and enhances user experience. 
Also I am Unsure of it that it will work fine or not. 😅
Should I Go with Formspree for now ?

**Comment by varshith257** [comment]
Ok! If you are strongly agreed to work on it. Let's go. I will ask @Anishkagupta04 for FormSpree id
