### ISSUE TITLE
Adding icons  for different sections on the navbar ,such as contact , about , services etc:-

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#76]
Adding icons for different sections on the navbar such as for doctors, services etc.

**Comment by Soumya6Tiwari** [comment]
@Anishkagupta04  kindly assign me this issue under gssoc'24

**Comment by Soumya6Tiwari** [comment]
@varshith257 I have already made the PR and it is merged

**Comment by varshith257** [comment]
Can you link the PR here ?

**Comment by Soumya6Tiwari** [comment]
@ #88
