### ISSUE TITLE
🐞[Bug]: Adding smooth scroll and padding

### ISSUE THREAD

**Issue by Archiesachin** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When clicked on the navlinks it does not smoothly navigates to that section. 
many elements don't have proper aligning and padding which is making it overflown with content

### Expected behavior

The elements should have proper padding and the text should not get overflown. 

## Misalignment

![Screenshot (1164)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/103347688/721ca160-4eea-48f6-89c6-c1555d9ba435)

![Screenshot (1168)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/103347688/094fe193-0a08-4148-bf11-6f0a776d31e5)

![Screenshot (1165)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/103347688/856eeaa4-670d-4ea9-9118-60f1bd4ece35)

## Padding not proper
![Screenshot (1166)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/103347688/2c4ce974-33fe-42b5-90e8-822a2cf02e1d)

![Screenshot (1167)](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/103347688/4f3ab319-f761-4b0b-b3d8-af086f058e79)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL
