### ISSUE TITLE
🐞[Bug]:  Absence of Navbar and Footer in Terms and Conditions

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @Anishkagupta04 and @varshith257 

On this website, the terms and conditions page does not have a navbar and footer.
I want to add a navbar and footer in the terms and conditions page for consistency across the website.

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/163530398/6e96ac4f-14e0-42ff-943b-369219d8cf47)

### Expected behavior

It should have navbar and footer.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
I think there is an open PR for it. Check it once

**Comment by varshith257** [comment]
Integrated with recent PR merge
