### ISSUE TITLE
✨[Feature Request]:  "Improve Hover Effects for Social Media Icons in Home Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Anishkagupta04 

Currently, the hover effects for our social media icons on the website are not optimal, lacking consistency and aesthetic appeal.

**Please add the gssoc and the required level labels and I would like to work on it under GSSoC'24. Thank you!!**

### Use Case

Visually appealing hover effects attract users' attention and encourage interaction with our social media links. This can lead to increased engagement and followership on our social media platforms.

Clear hover effects provide intuitive feedback, guiding users to understand that icons are clickable and encouraging them to explore our social media presence further.

### Add ScreenShots

Before making the changes:

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/159511364/a86e9c62-33ac-44a5-aa01-5aec33f1ffe4

After making the changes:

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/159511364/bec32158-500a-462f-8d73-cd684535da6b

**Please add the gssoc and the required level labels and I would like to work on it under GSSoC'24. Thank you!!**

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by avishek999** [comment]
i understand the problem,  i can make it look consistent and look good
