### ISSUE TITLE
🐞[Bug]: Appointment form has 2 age input field

### ISSUE THREAD

**Issue by ananyag309** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Appointment form has 2 age input field
![two](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/145869907/9c76a88d-1f51-4115-b200-7acbb33f965a)

### Expected behavior

remove extra age box

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
There are open PRs for appointment form fixing. Maybe this handled there, I haven't see any now in the open PR of it
