### ISSUE TITLE
✨[Feature Request]: Correct Copyright Text and Enhance Social Media Icons with Hover Effects in Service Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Anishkagupta04 

The current footer section of the website has two main issues:

- The copyright text in the footer is incorrect and does not belong to this project.
- The social media icons do not have a hover effect that changes their color to match their respective brand colors.

**Please add the gssoc and the required level labels and I would like to work on it under GSSoC'24. Thank you!!**

### Use Case

- Hover effects provide visual feedback, encouraging users to interact with the social media icons and follow the project's social media profiles.
- Having the correct copyright information ensures that the project is accurately represented and legally compliant.

### Add ScreenShots

This is screenshot related to the issue:
![Screenshot 2024-07-06 173119](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/159511364/d18ccbf7-c832-4586-b54b-f673d05afc8a)

**Please add the gssoc and the required level labels and I would like to work on it under GSSoC'24. Thank you!!**

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@SaiTejaswaniBikkasani Is the screenshot attached is the changes you are proposing?

**Comment by SaiTejaswaniBikkasani** [comment]
@varshith257 , I would like to add hover effect to the social media icons and also update the copyrights and the screenshot belongs to the current page like it belongs to the actual issue.
