### ISSUE TITLE
updated footer to new desgin

### ISSUE THREAD

**Issue by varun1903** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

updated footer a good desgin

### Use Case

using javascript and css

### Benefits

good attraction

### Add ScreenShots

dwd

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@varun1903 What are you thinking of changing? Add detailed description of issue

**Comment by avishek999** [comment]
please give full how you like to look like and i will try to make it
