### ISSUE TITLE
Add dark mode in login/register 

### ISSUE THREAD

**Issue by root-0101** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#783]
There is no dark mode in login/register section, adding dark will be great as it matches the existing theme of the website and improve user experience

![Screenshot 2024-07-06 225023](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142779809/e565b8f0-a113-4902-b624-c107d4b49e82)

**Comment by varshith257** [comment]
@root-0101 Here you go!

**Comment by root-0101** [comment]
done the changes please review the PR
