### ISSUE TITLE
Link github

### ISSUE THREAD

**Issue by root-0101** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#784]
There is no ULR of github in the contact github icon which affects the user engagement and create negative impact about the website 

![Screenshot 2024-07-06 224930](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142779809/66ea221f-e29b-4699-a827-be4f7b321f27)

**Comment by varshith257** [comment]
It has been integrated recently
