### ISSUE TITLE
Add search feature

### ISSUE THREAD

**Issue by root-0101** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#785]
It would be a great feature to add a search bar to find a doctor on the basic on their names which is help for user to view a specific doctor

![Screenshot 2024-07-06 225129](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142779809/f359e96d-5142-4ebc-b2aa-13a9eb073a45)

**Comment by 20username11** [comment]
Please assign me this issue
