### ISSUE TITLE
Add sort method 

### ISSUE THREAD

**Issue by root-0101** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#786]
It is very helpful to user to sort the doctors on basics of their profession. so, add a sorting method would be great

![Screenshot 2024-07-06 225129](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142779809/7d01a9d0-4d34-479d-8049-56acc256a706)

**Comment by neeraj542** [comment]
Hey there! I want to work on this issue, can assign me?

**Comment by 20username11** [comment]
I want to work on this issue please assign me this issue
