### ISSUE TITLE
✨[Feature Request]:  Add Cursor Trail Effect Matching to Website Design Theme Across All The Pages 

### ISSUE THREAD

**Issue by MastanSayyad** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @varshith257 

I would like to add a Cursor trail effect matching to the website design theme across all the pages of the website (for consistency)

**I will make sure:**

- It is smooth without lag.
- Aesthetically pleasing
- The trail effect does not interfere with other interactive elements on the page.
- It does not irritate to users instead it will be fun to play with!

### Use Case

Increases User Experience 

### Benefits

N/A

### Add ScreenShots

**Some examples of my works are:**

https://github.com/Indie-Kart/ecommerce-store/assets/101971980/9d9e741e-065e-4f65-893a-9a01b8ecba54

https://github.com/Indie-Kart/ecommerce-store/assets/101971980/2ec1964f-6ce8-4029-86f7-62d5df520211

https://github.com/Its-Aman-Yadav/Community-Site/assets/101971980/95dd3a00-a331-4cf3-ae8b-28319878190d

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@MastanSayyad It's been previously added my another contributor but Admin doesn't want it and removed
