### ISSUE TITLE
✨[Feature Request]: Addition of GOOGLE TRANSLATOR in the footer.

### ISSUE THREAD

**Issue by HishitaGupta** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of GOOGLE TRANSLATOR in the footer to make the website multilingual and more accessible.

### Use Case

Will help to view all the pages in different languages supported by google translator.

### Benefits

Will help to view all the pages in different languages supported by google translator.

### Add ScreenShots

![Screenshot 2024-06-21 115052](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/159264060/5828bc3e-3acb-4607-aa7c-469fbf9134a5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@HishitaGupta Before it added! But doesn't align with the project. Maybe header could be right place
