### ISSUE TITLE
✨[Feature Request]: Addition of SORT BY SPECIALIZATION on services page

### ISSUE THREAD

**Issue by HishitaGupta** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of SORT BY SPECIALIZATION on services page.

### Use Case

Will help the users to sort the doctors according to their specialisation like cardiology , gynaecology etc.

### Benefits

Will help the users to sort the doctors according to their specialisation like cardiology , gynaecology etc.

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/159264060/69fee825-6bad-471d-934a-9362a445af30)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@HishitaGupta There is an open issue for it
