### ISSUE TITLE
🐞[Bug]:  CSS of website in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142989448/01b47c65-bf44-46a6-bd40-102efeb2d149)

fixing css

### Expected behavior

fixed margin and all

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dhairyagothi** [comment]
@Anishkagupta04 please assign  me

**Comment by varshith257** [comment]
@dhairyagothi level 3 to fix whole  home page into mobile responsiveness

**Comment by varshith257** [comment]
You can also make follow up PRS for other pages too for mobile responsiveness and will award each PR separately
