### ISSUE TITLE
🐞[Bug]: Footer Hover Text Color is Black, Change Footer Hover Text Color for Better Visibility

### ISSUE THREAD

**Issue by AsmitaMishra24** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The current hover text color in the footer is black, which blends with the background, making the text difficult to read. To improve visibility and maintain consistency, the hover text color in the footer should be updated to match the hover text color used in the navbar.

### Expected behavior

The text should change to a color that is clearly visible against the background, similar to the hover color used in the navbar.

### Add ScreenShots

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146121869/92352949-92c8-437d-be4a-d6a3af13fb00

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AsmitaMishra24** [comment]
@varshith257, please assign this issue.

**Comment by Soujanya2004** [comment]
hi, I would like to work on this issue, can u plz assign me

**Comment by varshith257** [comment]
@Soujanya2004 Better I recommend to see old issues which are open from a month

**Comment by varshith257** [comment]
@AsmitaMishra24 has already raised this issue and commented her interest. So we need to assign her

**Comment by Soujanya2004** [comment]
sure
