### ISSUE TITLE
✨[Feature Request]:  News Section Hover Effect

### ISSUE THREAD

**Issue by Damini2004** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hover Effect advancement

### Use Case

Hover Effect advancement

### Benefits

Hover Effect advancement

### Add ScreenShots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/119414762/656548b0-cbf8-41bc-9a7d-3e937c2a8eb6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
Isn't it already present @Damini2004

**Comment by avishek999** [comment]
assign me i can do it
