### ISSUE TITLE
🐞[Bug]:  twitter link is not redirecting

### ISSUE THREAD

**Issue by Soujanya2004** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The twitter link in service page footer is not redirecting 

### Expected behavior

redirect to twitter page

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@Soujanya2004 We have no twitter account yet :)
