### ISSUE TITLE
🐞[Bug]: Add Footer and Navbar in the Terms and Condition Page

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @varshith257 

There is an absence of footer in terms and condition page 
For consistency across to the website I would like add a footer just like home page T and c page

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/163530398/cf183d72-5460-42e9-a0e5-53bb6a2ffcf2)

Please assign this issue to me Under GSSOC24?

### Expected behavior

N/A

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@RadhikaMalpani1702 Add navbar too
