### ISSUE TITLE
🐞[Bug]: Text in subscribe button is not clearly visible

### ISSUE THREAD

**Issue by Soujanya2004** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

make the text inside the subscribe button visible clearly

### Expected behavior

change text color

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dharna27** [comment]
I would like to work on this project. Please assign this issue to me.

**Comment by Soujanya2004** [comment]
@varshith257 please review PR
