### ISSUE TITLE
🐞[Bug]: add hover effects to footer

### ISSUE THREAD

**Issue by Soujanya2004** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 add hover effects to links in footer section in service page

### Expected behavior

underline text on hovering

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@Soujanya2004 I think a issue is open for this. Can you verify and tag me?

**Comment by Soujanya2004** [comment]
@varshith257 issue is not open for this, I have checked

**Comment by Soujanya2004** [comment]
please add level for the PR @varshith257
