### ISSUE TITLE
✨[UI Enhancement]: I would like to enhance the ui of the login page  

### ISSUE THREAD

**Issue by aditya-bhaumik** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i would like to enhance the ui of the login page

### Use Case

Before : 
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/92214013/b3fecb8b-b0bf-49fd-a8db-8d3fd887ac66)

After : 
![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/92214013/4801c5ae-581f-4755-a222-29f0b960664c)
I will make some more changes but this is the first change i made to the ui i will also change the design a little of the containers
This is going to be a moving background which will be a little blurry so that the containers are more visible

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@aditya-bhaumik But we need to modify this to match our project color scheme

**Comment by aditya-bhaumik** [comment]
@varshith257 okay i will change the background to something which matches the project color scheme 
and improve the ui of the containers
