### ISSUE TITLE
✨[Feature Request]: Add a google translate button 

### ISSUE THREAD

**Issue by samarsajad** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adda google translate option as a popup that is fully aligned with the website theme

### Use Case

a good UI feature that translates pages in trhe preferred language

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by samarsajad** [comment]
Please assign this issue to me @varshith257 @Anishkagupta04

**Comment by varshith257** [comment]
Please take care off appropriate place to keep it in. Recently it added but removed due to conflict of placing it in wrong g place in homepage

**Comment by samarsajad** [comment]
> Please take care off appropriate place to keep it in. Recently it added but removed due to conflict of placing it in wrong g place in homepage

I placed it along the same line with chat bot and top-to-down but to the left side. Plus it is like the popup similar to chat bot and top to bottom, so it won't disappear. Also, the styles used are catered to the website theme and is not a basic translate option. Please take a look at my pull request concerning this issue #869
