### ISSUE TITLE
🐞[Bug]: Changing the styling of Heading tags to make them visible

### ISSUE THREAD

**Issue by bharat-c27** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As you can see that the heading section are not visible, so I will figure out the issue and applying the required styling to make it visible

### Expected behavior

I will figure out the cause for the isssue and work on the styling 

### Add ScreenShots

https://github.com/user-attachments/assets/df0414aa-d2eb-4d7b-81d7-b215aa2a8704

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by bharat-c27** [comment]
Hello @varshith257 can you please assign the issue.

Thank you!!

**Comment by Kishita16** [comment]
Hi @varshith257 can you please assign the issue

**Comment by varshith257** [comment]
@Kishita16 It's already assigned to @bharat-c27 . I recommend you to go through old issues opened a long back and tag me there if you are willing to work on them

**Comment by Kishita16** [comment]
Okay! 
Thank you
