### ISSUE TITLE
🐞[Bug]: Text not visible in footer

### ISSUE THREAD

**Issue by Soujanya2004** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the subscribe button in the footer of home page has to be changed to dark color to enhance visibility.

### Expected behavior

Text inside subscribe button will be enhanced

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
Can you assign me this issue

**Comment by dharna27** [comment]
I would like to work on this project. Please assign it to me.
