### ISSUE TITLE
[ Priority] Make Website Mobile Responsive 

### ISSUE THREAD

**Issue by varshith257** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#894]
We are introducing a new series of issue. It works as parent issue for all. 

**Requirements:**

1) Make all pages mobile responsive 
2) Navbar of every page should align with home page and mobile responsive 
3) Footer also need to be align with the homepage footer.
4) Every change should adhere to color scheme of website.

**Note:**

- This works as parent issue. Don't ask for assign. 

- Submit a PR directly with appropriate changes to make a page mobile responsive.

- Each contributor can submit any number of PRs. Each for a page to make mobile responsive.

-  Each PR will be awarded level 3 for it.

**Comment by varshith257** [comment]
cc:
@Pruthaa17 @Asymtode712 @Anjaliavv51 @richasriva  @PradnyaGaitonde @Arpcoder @MastanSayyad @Hemashree21 @aditya-bhaumik @ShahHetviIT @TejaswiKandunuri @bharat-c27 @Soujanya2004 @Damini2004 @sidhigrover @Kriagr23 


Just I tagged some of you to get immediate attention for this.

PS: Feel free to submit PR anyone not only explicit Mentioned in above. I would like to see new contributers to work on them and share to your friends too.


This week and next week we are only focusing on mobile responsiveness and big fixes across project and role our road to Release beta version of project very soon :)

**Comment by varshith257** [comment]
Just comment here the page name you are going to work and /assign. Something like below.

- Home page
/assign

**Comment by aditya-bhaumik** [comment]
@varshith257 how many pages can we work on at a time

**Comment by Anjaliavv51** [comment]
* Home page
   /assign

**Comment by aditya-bhaumik** [comment]
- faq page 

/assign

**Comment by varshith257** [comment]
> @varshith257 how many pages can we work on at a time 

Each page a PR. Feel free to submit any number of PRs to make all pages mobile responsiveness.

But should comment here what you working on. After successful submission of your PR and comment here for another page 

_Note_:
You may not get immediate attention from me for you PR but suit a PR with appropriate changes to make page mobile responsiveness and comment here for another page and submit another PR and so on...

**Comment by aditya-bhaumik** [comment]
@varshith257 okay i will starting working on the pages now

**Comment by meetarora10** [comment]
services page
/assign

**Comment by MastanSayyad** [comment]
- News page
/assign

**Comment by Anjaliavv51** [comment]
* Doctor Experience
/assign

**Comment by Anjaliavv51** [comment]
* Signup Page
/assign

**Comment by meetarora10** [comment]
Book an appointment page
/assign

**Comment by varshith257** [comment]
Hey everyone don't race on the track to get more pages 😅. Submit a PR and then comment here to work on another page. It could give everyone equally a chance to contribute :)

**Comment by samarsajad** [comment]
News page
/assign

**Comment by samarsajad** [comment]
News Page
/assign

**Comment by varshith257** [comment]
@samarsajad I think @MastanSayyad is working on it. Check for new one

**Comment by sailaja-adapa** [comment]
footer
/assign

**Comment by samarsajad** [comment]
> @samarsajad I think @MastanSayyad is working on it. Check for new one 

I have already raised issues for the service page & the patient portal & they were assigned to me. So should I just work on them?

**Comment by varshith257** [comment]
@MastanSayyad Have a look at it and maybe @samarsajad can work on it as already assigned in issue before

**Comment by Asymtode712** [comment]
Hey @varshith257 are all the pages assigned??

**Comment by sailaja-adapa** [comment]
About Page
/assign

**Comment by sailaja-adapa** [comment]
Rate us page
/assign

**Comment by varshith257** [comment]
No just it's exception of the @samarsajad as already assigned to.two issues before. Feel free to work on other page which hasn't commented here and verify same in the website which needed to be work on

**Comment by MastanSayyad** [comment]
> @MastanSayyad Have a look at it and maybe @samarsajad can work on it as already assigned to issue before 

If she wants to she can, i have no objection

**Comment by MastanSayyad** [comment]
I'll look for some other pages which are not mentioned here!

**Comment by Asymtode712** [comment]
@varshith257 I would like to work on "derma" doctor page

**Comment by Asymtode712** [comment]
@varshith257 I would like to work on "ent" doctor page

**Comment by MastanSayyad** [comment]
I have started working on blood test page @varshith257

**Comment by aditya-bhaumik** [comment]
@meetarora10 don't link the pull request with the issue as it will close the issue

only mention it remove fixes

**Comment by varshith257** [comment]
It will be better add as Part of #XXX

**Comment by meetarora10** [comment]
> @meetarora10 don't link the pull request with the issue as it will close the issue
> 
> only mention it
> 
> remove fixes

Okay 👍👍

**Comment by varshith257** [comment]
Merged a PR. Just take this reference for navbar and footer alignment for mobile responsive 

- https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/pull/895

**Comment by Soujanya2004** [comment]
services section
/assign

**Comment by Soujanya2004** [comment]
input page
/assign

**Comment by Damini2004** [comment]
Appointment Page
/assign

![image](https://github.com/user-attachments/assets/16af8c79-3ce8-4007-b296-e71585ef52c7)

**Comment by meetarora10** [comment]
> Book an appointment page /assign

@Damini2004 I have taken this page .

**Comment by meetarora10** [comment]
cardio page
/assign

**Comment by Damini2004** [comment]
patient portal 
/assign 
![image](https://github.com/user-attachments/assets/29970152-2e1a-410e-96b3-c93cb961c55e)

**Comment by Soujanya2004** [comment]
![Screenshot (128)](https://github.com/user-attachments/assets/a657c07b-f87a-4afa-8f05-4bd32172ed5c)
done,

**Comment by Damini2004** [comment]
i want to work on Gynecologist section @varshith257

**Comment by Damini2004** [comment]
i want to work on Pediatrician section @varshith257

**Comment by aditya-bhaumik** [comment]
guys please first work on one page then take another page so that other contributors also have fair chance  

@varshith257 please add this rule also that a person can only work on one page a time as there are some who are taking 2 or 3

**Comment by sailaja-adapa** [comment]
/contact
assign

**Comment by meetarora10** [comment]
Privacy Policy page
/assign

**Comment by PradnyaGaitonde** [comment]
Terms & Conditions Page
/assign

**Comment by Anjaliavv51** [comment]
Want to decrease the size of © 2024 RapiDoc | All Rights Reserved Made with ❤ by RapiDoc in every page of the repo.

/assign

**Comment by varshith257** [comment]
Will review all this PRS of this issue and merge on Wednesday.

Thank you for the work done with immediate attention and for your persistence on this issue to get solved.

**Comment by varshith257** [comment]
I highly recommend everyone to join project slack channel mentioned in the Readme.md

Once this project got stabilised we are getting to a new a project building from scratch of a production website(Currently on the planning stage with potential investors on it)

The aim of my mentoring is to quickly make you to delve into production organisations, contribute them and can aim for GOOGLE SUMMER OF CODE(GSOC) 2025 by end of Gssoc'24

**Comment by aditya-bhaumik** [comment]
@varshith257 i guess the link is no longer active

**Comment by varshith257** [comment]
https://join.slack.com/t/rapidocworkspace/shared_invite/zt-2n0yjah2u-rhaBvo3uSo0uAn4fyhgE1w

**Comment by aditya-bhaumik** [comment]
@Damini2004 remove closes from your pull request as merging it will cause this issue to close

**Comment by Damini2004** [comment]
@aditya-bhaumik sure

**Comment by meetarora10** [comment]
> Will review all this PRS of this issue and merge on Wednesday.
> 
> Thank you for the work done with immediate attention and for your persistence on this issue to get solved.
> 
> Till then you can do peer reviewes (get to another contributors PRs and check their changes and suggest any improvements if needed according to issue requirements)

@varshith257 when the PR's will be reviewed ?

**Comment by Soujanya2004** [comment]
please assign so that the points will be given for this PR

**Comment by Soujanya2004** [comment]
please add assignees @Anjaliavv51

**Comment by Soujanya2004** [comment]
> please assign so that the points will be given for this PR

@varshith257 @Anjaliavv51

**Comment by varshith257** [comment]
@Soujanya2004 It is not needed to assign a issue
