### ISSUE TITLE
✨[Feature Request]: add a testimonail page

### ISSUE THREAD

**Issue by aditya-bhaumik** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a testimonial page as the current link in the footer is not directing us to any other page it just takes us back to the top of the screen

### Use Case

Build Trust: Displaying testimonials from satisfied users or clients helps build trust with new visitors.
Showcase Success: Highlighting positive feedback and success stories can encourage potential users to engage with your website or services.
Engage Users: Testimonials provide social proof and can be an effective way to engage with your audience.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by aditya-bhaumik** [comment]
@varshith257 please assign me this issue

**Comment by varshith257** [comment]
I think the better fix is to redirect to testimonials section in home page. I have a good design idea for it.

We need to support to display more testimonials on home page. Something like we needed to display one testimonial first on home page and follow up with the a delay time we need to display other testimonials.

We need < and > buttons which enables user to click on them to move left and right of testimonials

**Comment by aditya-bhaumik** [comment]
> I think the better fix is to redirect to testimonials section in home page. I have a good design idea for it.
> 
> We need to support to display more testimonials on home page. Something like we needed to display one testimonial first on home page and follow up with the a delay time we need to display other testimonials.
> 
> We need < and > buttons which enables user to click on them to move left and right of testimonials

okay i understood will make the changes and add the pull request by this weekend
