### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by pankaj-bind** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#9]
Documentation is missing, without any proper documentation it is hard to setup project in our system.
Assign me this task under GSSoC'24, I will implement it.

**Comment by SanjanaBankar** [comment]
Hello,

Upon reviewing the current README for RapiDoc, I've identified opportunities to enhance engagement, informativeness, and user-friendliness. To address this, I propose restructuring content with clear headings, concise descriptions, and visually appealing formatting. Additionally, emphasizing engagement with clear instructions for contributions and feedback will make a more collaborative environment. Integrating relevant visual assets such as images or diagrams will effectively showcase RapiDoc's capabilities. 

I'm looking forward to the opportunity to contribute to the RapiDoc platform. If possible please assign me this task under GSSoC24.

**Comment by Anishkagupta04** [comment]
Assigning

**Comment by SanjanaBankar** [comment]
> Assigning

Hello, can you please update the assignees so that I can start working?

**Comment by kanikaa-3018** [comment]
hey pls assign me this project for GSSoc'24

**Comment by SohaFarhana** [comment]
Hello
I am a GSSoC'24 contributor and looking forward to work on this

**Comment by TejaswiKandunuri** [comment]
@Anishkagupta04, I am ready to do this documentation work on Rapidoc health care website for you. please assign this work to me.

**Comment by varshith257** [comment]
@pankaj-bind Are you willing to add a separate documentation or just add setup process in README?

**Comment by varshith257** [comment]
@SanjanaBankar Are you willing to work on this?

**Comment by SanjanaBankar** [comment]
> @SanjanaBankar Are you willing to work on this?

Hello, @varshith257 I already have a prior issue lined up, It would be great if other interested contributors work on this.

**Comment by varshith257** [comment]
@TejaswiKandunuri Are you willing to work on this?

**Comment by TejaswiKandunuri** [comment]
> @TejaswiKandunuri Are you willing to work on this?

Yes, i am willing to work on this

**Comment by TejaswiKandunuri** [comment]
Thank you, i will start working on it.

**Comment by TejaswiKandunuri** [comment]
Hi,
Do you have any template for documentation or should i take some other
template and work on it?

**Comment by TejaswiKandunuri** [comment]
> > Hi,
> > Do you have any template for documentation or should i take some other
> > template and work on it?
> 
> No specified. If you have any in your mind post here, let's evaluate of selection of template
Please take a look at these sections that I am considering including in the documentation.
RAPIDOC-HEALTHCARE-WEBSITE
Documentation Table of Contents
1.Project Overview
2.Objectives
3.Purpose
4.Features
5.Technology Stack
6.Architecture
7.Installation (Prerequisites, Setup)_
8.Usage
9.Advantages
10.Disadvantages
11.Future Scope
12.Conclusion

**Comment by TejaswiKandunuri** [comment]
Thanks, I will.

**Comment by TejaswiKandunuri** [comment]
@varshith257 I added documentation. please take a look and kindly add GSSOC points.
