### ISSUE TITLE
Mini ChatBot Addition

### ISSUE THREAD

**Issue by hollermay** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#91]
Addition to add a mini chatbot at below right of the home page to answer queries and also provide relevant links based on the queries asked from the bot. 

I can build this dedicated bot using either FASTAPI or another open-source technology in order to implement it. LLMs can also be utilized for this.

**Comment by Anishkagupta04** [comment]
assigning

**Comment by Vaibhav22p-qw** [comment]
hello @varshith257  Please assign me to add chat bot feature in your project @hollermay didn't Start to work
(Under GSSoC'24)

**Comment by hollermay** [comment]
@Vaibhav22p-qw bro I'm working on it. -_-

**Comment by Vaibhav22p-qw** [comment]
> @Vaibhav22p-qw bro I'm working on it. -_-

Ohk

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.
