### ISSUE TITLE
✨Add Icons to Footer

### ISSUE THREAD

**Issue by sailaja-adapa** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to add icons to Footer to make our website to look Attractive
Can you assign me this issue under GSSOC'24 @varshith257

### Use Case

it will enhance user experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by varshith257** [comment]
@sailaja-adapa Maybe in footer it doesn't look good with icons

**Comment by sailaja-adapa** [comment]
Yeah okk @varshith257

**Comment by sailaja-adapa** [comment]
I would like to connect on LinkedIn
What's your LinkedIn profile link

**Comment by varshith257** [comment]
[LinkedIn Profile](https://www.linkedin.com/in/vamshi-maskuri?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app)
