### ISSUE TITLE
💡[FEATURE]:  Redirect to dialer pad

### ISSUE THREAD

**Issue by pankaj-bind** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#92]
**Describe the solution you'd like**
When user clicks on the phone number it will redirect them to their phone's dialer-pad, and they can take quick action.

**Additional context**
Assign me this work under GSSoC24, I will implement it.

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/73558583/57e8c6bc-2e99-40eb-bf98-d74bc68530df)

**Comment by Anishkagupta04** [comment]
assigning

**Comment by pankaj-bind** [comment]
> assigning

I didn't understand.

**Comment by Anishkagupta04** [comment]
you can do this

**Comment by pankaj-bind** [comment]
@varshith257 can you guide me how to run this project in my system, it is not like normal html, css, js file.

**Comment by Vaibhav22p-qw** [comment]
hello @varshith257 Please assign me this work i'm free right now and @pankaj-bind is not understand about projects (in github)
@pankaj-bind is also not forked this

**Comment by Anishkagupta04** [comment]
@Vaibhav22p-qw  assigning to you

**Comment by Vaibhav22p-qw** [comment]
@Anishkagupta04 Thankyou for Assigning me

**Comment by Vaibhav22p-qw** [comment]
Submitting as soon as possible

**Comment by Vaibhav22p-qw** [comment]
hello @varshith257  & @Anishkagupta04 any other issue to fix (under GSSoC'24) please prefer to me
