### ISSUE TITLE
✨[Feature Request]: Add hover effect to Find A Doctor button on the navbar of home page

### ISSUE THREAD

**Issue by ahinagangopadhyay** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Find a Doctor button does not have any colour change effect on hovering.I would like to add a colour change hover effect to the button.Please assign me this issue under GSSOC 2024.
![Screenshot (28)](https://github.com/user-attachments/assets/b2b6740d-9c7f-4d19-811d-999b115cdbeb)

### Use Case

The feture would improve the design of the website.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by anshulagr5** [comment]
I would like to work on this issue. Kindly assign it to me.
