### ISSUE TITLE
✨[Feature Request]: I want to add "submitted successfully" popup in patient portal

### ISSUE THREAD

**Issue by Maana-Ajmera** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When patient adds username and password , and clicks submit ,  a popup should come "submitted successfully"

### Use Case

It will make our website more user-friendly

### Add ScreenShots

https://github.com/user-attachments/assets/fcfec48d-a587-4dc7-aba0-afc2af087de2

Similar to this but , the text would be "submitted sucessfully"
![image](https://github.com/user-attachments/assets/3bf27507-dd59-4f73-b36c-9e24ba8f63f7)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maana-Ajmera** [comment]
@varshith257 Please assign it to me

**Comment by Anishkagupta04** [comment]
Assigning
