### ISSUE TITLE
missing code of conduct 

### ISSUE THREAD

**Issue by prajwaldp223** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#95]
this repo is missing with the code of conduct file and i acn do it is assigned to me under gssoc !!

**Comment by Anishkagupta04** [comment]
assigning to you

**Comment by prajwaldp223** [comment]
@Anishkagupta04 ,can u assign this to me under gssoc label?

**Comment by varshith257** [comment]
@prajwaldp223 Closing as duplicate of  
- #16

**Comment by prajwaldp223** [comment]
@varshith257 !!
should i raise sepetate for both?

**Comment by prajwaldp223** [comment]
ok

**Comment by prajwaldp223** [comment]
but the other one is named as duplicate!! can u recheck it!! as i have deleted a file PRfile from request and crated new PR #111

**Comment by varshith257** [comment]
Check PR #16
