### ISSUE TITLE
✨[Feature Request]: A message display "we will connect you soon "  when someone fills contact form 

### ISSUE THREAD

**Issue by ANKeshri** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A message display "we will connect you soon "  when someone fills contact form 

### Use Case

giving user info that message has been sent 

### Benefits

A message display "we will connect you soon "  when someone fills contact form 

### Add ScreenShots

https://github.com/user-attachments/assets/7ef753a4-7c47-4afe-b614-2cce2f668c9a

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@varshith257 please assign me this issue

**Comment by ANKeshri** [comment]
@varshith257 @Anishkagupta04 please assign me this issue

**Comment by ANKeshri** [comment]
@varshith257 please assign me this issue

**Comment by ANKeshri** [comment]
@varshith257 please let me know should i work on it or close this issue

**Comment by varshith257** [comment]
@ANKeshri Go ahead!
