### ISSUE TITLE
lacks a pull request template file

### ISSUE THREAD

**Issue by prajwaldp223** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#96]
# Pull Request Template

## Type of Change
- [ ] Bug Fix
- [ ] Enhancement
- [ ] Documentation Change

## Checklist
- [ ] Part of GSSOC
- [ ] Tested for any breaking changes
- [ ] Other relevant checks completed

## Contributor Agreement
- [ ] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by prajwaldp223** [comment]
i can fix it if assigned to me under gssoc !!!

**Comment by Anishkagupta04** [comment]
assigning to you

**Comment by prajwaldp223** [comment]
issue fixed!!
@varshith257

**Comment by varshith257** [comment]
@prajwaldp223 Make PR to this repo. Not to your forked repo and merge there

**Comment by prajwaldp223** [comment]
okay!! i will delete that

**Comment by prajwaldp223** [comment]
now?
