### ISSUE TITLE
✨[Feature Request]: Make services page responsive 

### ISSUE THREAD

**Issue by ANKeshri** [Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

make services page responsive

### Use Case

responsieness

### Benefits

looks good 

### Add ScreenShots

Uploading Recording 2024-07-25 215541.mp4…

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@varshith257 please assign me this issue

**Comment by varshith257** [comment]
I think there is a open PR for it

**Comment by ANKeshri** [comment]
> I think there is a open PR for it

sure i am closing this sorry
